// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: hub/v1/query.proto

package types

import (
	_ "github.com/TrueOpen/cortex/proto/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hub_v1_query_proto protoreflect.FileDescriptor

const file_hub_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x12hub/v1/query.proto\x12\x06hub.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19hub/v1/query_bridge.proto\x1a\x1bhub/v1/query_registry.proto\x1a\x1ahub/v1/query_rewards.proto2\xbd'\n" +
	"\x05Query\x12h\n" +
	"\x06Params\x12\x1d.hub.v1.QueryHubParamsRequest\x1a\x1e.hub.v1.QueryHubParamsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/TrueOpen/hub/v1/params\x12k\n" +
	"\x06Beacon\x12\x1a.hub.v1.QueryBeaconRequest\x1a\x1b.hub.v1.QueryBeaconResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /TrueOpen/hub/v1/beacon/{height}\x12v\n" +
	"\x06VrfKey\x12\x1a.hub.v1.QueryVrfKeyRequest\x1a\x1b.hub.v1.QueryVrfKeyResponse\"3\x82\xd3\xe4\x93\x02-\x12+/TrueOpen/hub/v1/vrf_key/{operator_address}\x12\xbd\x01\n" +
	"\n" +
	"BuilderSet\x12\x1e.hub.v1.QueryBuilderSetRequest\x1a\x1f.hub.v1.QueryBuilderSetResponse\"n\x82\xd3\xe4\x93\x02hZ5\x123/TrueOpen/hub/v1/builder_set/by_id/{builder_set_id}\x12//TrueOpen/hub/v1/builder_set/by_height/{height}\x12x\n" +
	"\aBuilder\x12\x1b.hub.v1.QueryBuilderRequest\x1a\x1c.hub.v1.QueryBuilderResponse\"2\x82\xd3\xe4\x93\x02,\x12*/TrueOpen/hub/v1/builder/{builder_address}\x12j\n" +
	"\bBuilders\x12\x1c.hub.v1.QueryBuildersRequest\x1a\x1d.hub.v1.QueryBuildersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/TrueOpen/hub/v1/builders\x12i\n" +
	"\x05Fault\x12\x19.hub.v1.QueryFaultRequest\x1a\x1a.hub.v1.QueryFaultResponse\")\x82\xd3\xe4\x93\x02#\x12!/TrueOpen/hub/v1/fault/{fault_id}\x12t\n" +
	"\bEarnings\x12\x1c.hub.v1.QueryEarningsRequest\x1a\x1d.hub.v1.QueryEarningsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/TrueOpen/hub/v1/earnings/{address}\x12i\n" +
	"\x05Model\x12\x19.hub.v1.QueryModelRequest\x1a\x1a.hub.v1.QueryModelResponse\")\x82\xd3\xe4\x93\x02#\x12!/TrueOpen/hub/v1/model/{model_id}\x12b\n" +
	"\x06Models\x12\x1a.hub.v1.QueryModelsRequest\x1a\x1b.hub.v1.QueryModelsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/TrueOpen/hub/v1/models\x12\x83\x01\n" +
	"\aProfile\x12\x1b.hub.v1.QueryProfileRequest\x1a\x1c.hub.v1.QueryProfileResponse\"=\x82\xd3\xe4\x93\x027\x125/TrueOpen/hub/v1/profile/{model_id}/{profile_version}\x12\x86\x01\n" +
	"\n" +
	"CortexNode\x12\x1e.hub.v1.QueryCortexNodeRequest\x1a\x1f.hub.v1.QueryCortexNodeResponse\"7\x82\xd3\xe4\x93\x021\x12//TrueOpen/hub/v1/cortex_node/{operator_address}\x12\x8a\x01\n" +
	"\vServiceBond\x12\x1f.hub.v1.QueryServiceBondRequest\x1a .hub.v1.QueryServiceBondResponse\"8\x82\xd3\xe4\x93\x022\x120/TrueOpen/hub/v1/service_bond/{operator_address}\x12\xa2\x01\n" +
	"\x11ServiceUnbondings\x12%.hub.v1.QueryServiceUnbondingsRequest\x1a&.hub.v1.QueryServiceUnbondingsResponse\">\x82\xd3\xe4\x93\x028\x126/TrueOpen/hub/v1/service_unbondings/{operator_address}\x12\xb6\x01\n" +
	"\x11CurrentServiceKey\x12%.hub.v1.QueryCurrentServiceKeyRequest\x1a&.hub.v1.QueryCurrentServiceKeyResponse\"R\x82\xd3\xe4\x93\x02L\x12J/TrueOpen/hub/v1/current_service_key/{participant_type}/{operator_address}\x12\xb5\x01\n" +
	"\x11ServiceDescriptor\x12%.hub.v1.QueryServiceDescriptorRequest\x1a&.hub.v1.QueryServiceDescriptorResponse\"Q\x82\xd3\xe4\x93\x02K\x12I/TrueOpen/hub/v1/service_descriptor/{participant_type}/{operator_address}\x12\x9e\x01\n" +
	"\x10ServiceLifecycle\x12$.hub.v1.QueryServiceLifecycleRequest\x1a%.hub.v1.QueryServiceLifecycleResponse\"=\x82\xd3\xe4\x93\x027\x125/TrueOpen/hub/v1/service_lifecycle/{operator_address}\x12\xa5\x01\n" +
	"\x0fModelCapability\x12#.hub.v1.QueryModelCapabilityRequest\x1a$.hub.v1.QueryModelCapabilityResponse\"G\x82\xd3\xe4\x93\x02A\x12?/TrueOpen/hub/v1/model_capability/{operator_address}/{model_id}\x12\x99\x01\n" +
	"\fModelSupport\x12 .hub.v1.QueryModelSupportRequest\x1a!.hub.v1.QueryModelSupportResponse\"D\x82\xd3\xe4\x93\x02>\x12</TrueOpen/hub/v1/model_support/{operator_address}/{model_id}\x12\x96\x01\n" +
	"\fDailySupport\x12 .hub.v1.QueryDailySupportRequest\x1a!.hub.v1.QueryDailySupportResponse\"A\x82\xd3\xe4\x93\x02;\x129/TrueOpen/hub/v1/daily_support/{operator_address}/{epoch}\x12\x9c\x01\n" +
	"\x14CurrentCandidatePool\x12(.hub.v1.QueryCurrentCandidatePoolRequest\x1a).hub.v1.QueryCurrentCandidatePoolResponse\"/\x82\xd3\xe4\x93\x02)\x12'/TrueOpen/hub/v1/candidate_pool/current\x12\xae\x01\n" +
	"\x15CandidatePoolSnapshot\x12).hub.v1.QueryCandidatePoolSnapshotRequest\x1a*.hub.v1.QueryCandidatePoolSnapshotResponse\">\x82\xd3\xe4\x93\x028\x126/TrueOpen/hub/v1/candidate_pool/snapshot/{snapshot_id}\x12\xc0\x01\n" +
	"\x13CandidatePoolMember\x12'.hub.v1.QueryCandidatePoolMemberRequest\x1a(.hub.v1.QueryCandidatePoolMemberResponse\"V\x82\xd3\xe4\x93\x02P\x12N/TrueOpen/hub/v1/candidate_pool/snapshot/{snapshot_id}/member/{candidate_slot}\x12\xb3\x01\n" +
	"\x14CandidatePoolMembers\x12(.hub.v1.QueryCandidatePoolMembersRequest\x1a).hub.v1.QueryCandidatePoolMembersResponse\"F\x82\xd3\xe4\x93\x02@\x12>/TrueOpen/hub/v1/candidate_pool/snapshot/{snapshot_id}/members\x12\xa3\x01\n" +
	"\x10CompetitionEpoch\x12$.hub.v1.QueryCompetitionEpochRequest\x1a%.hub.v1.QueryCompetitionEpochResponse\"B\x82\xd3\xe4\x93\x02<\x12:/TrueOpen/hub/v1/competition_epoch/{reward_bucket}/{epoch}\x12\xa8\x01\n" +
	"\x11RewardEpochCursor\x12%.hub.v1.QueryRewardEpochCursorRequest\x1a&.hub.v1.QueryRewardEpochCursorResponse\"D\x82\xd3\xe4\x93\x02>\x12</TrueOpen/hub/v1/reward_epoch_cursor/{epoch}/{reward_bucket}\x12\xab\x01\n" +
	"\x10RewardEpochAudit\x12$.hub.v1.QueryRewardEpochAuditRequest\x1a%.hub.v1.QueryRewardEpochAuditResponse\"J\x82\xd3\xe4\x93\x02D\x12B/TrueOpen/hub/v1/reward_epoch_audit/{source_epoch}/{reward_bucket}\x12j\n" +
	"\bTreasury\x12\x1c.hub.v1.QueryTreasuryRequest\x1a\x1d.hub.v1.QueryTreasuryResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/TrueOpen/hub/v1/treasury\x12{\n" +
	"\fBridgeStatus\x12 .hub.v1.QueryBridgeStatusRequest\x1a!.hub.v1.QueryBridgeStatusResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/TrueOpen/hub/v1/bridge/status\x12\xb3\x01\n" +
	"\x15ValidatorBridgeSigner\x12).hub.v1.QueryValidatorBridgeSignerRequest\x1a*.hub.v1.QueryValidatorBridgeSignerResponse\"C\x82\xd3\xe4\x93\x02=\x12;/TrueOpen/hub/v1/bridge/validator_signer/{operator_address}\x12\x8e\x01\n" +
	"\fFreezeSignal\x12 .hub.v1.QueryFreezeSignalRequest\x1a!.hub.v1.QueryFreezeSignalResponse\"9\x82\xd3\xe4\x93\x023\x121/TrueOpen/hub/v1/freeze_signal/{freeze_signal_id}\x12\xa5\x01\n" +
	"\rFreezeSignals\x12!.hub.v1.QueryFreezeSignalsRequest\x1a\".hub.v1.QueryFreezeSignalsResponse\"M\x82\xd3\xe4\x93\x02G\x12E/TrueOpen/hub/v1/freeze_signals/{model_id}/{profile_version}/{status}\x12\xaf\x01\n" +
	"\x14EmergencyFreezeVotes\x12(.hub.v1.QueryEmergencyFreezeVotesRequest\x1a).hub.v1.QueryEmergencyFreezeVotesResponse\"B\x82\xd3\xe4\x93\x02<\x12:/TrueOpen/hub/v1/emergency_freeze_votes/{freeze_signal_id}\x12\x8c\x01\n" +
	"\rTimeoutBucket\x12!.hub.v1.QueryTimeoutBucketRequest\x1a\".hub.v1.QueryTimeoutBucketResponse\"4\x82\xd3\xe4\x93\x02.\x12,/TrueOpen/hub/v1/timeout_bucket/{bucket_key}B&Z$github.com/TrueOpen/node/x/hub/typesb\x06proto3"

var file_hub_v1_query_proto_goTypes = []any{
	(*QueryHubParamsRequest)(nil),              // 0: hub.v1.QueryHubParamsRequest
	(*QueryBeaconRequest)(nil),                 // 1: hub.v1.QueryBeaconRequest
	(*QueryVrfKeyRequest)(nil),                 // 2: hub.v1.QueryVrfKeyRequest
	(*QueryBuilderSetRequest)(nil),             // 3: hub.v1.QueryBuilderSetRequest
	(*QueryBuilderRequest)(nil),                // 4: hub.v1.QueryBuilderRequest
	(*QueryBuildersRequest)(nil),               // 5: hub.v1.QueryBuildersRequest
	(*QueryFaultRequest)(nil),                  // 6: hub.v1.QueryFaultRequest
	(*QueryEarningsRequest)(nil),               // 7: hub.v1.QueryEarningsRequest
	(*QueryModelRequest)(nil),                  // 8: hub.v1.QueryModelRequest
	(*QueryModelsRequest)(nil),                 // 9: hub.v1.QueryModelsRequest
	(*QueryProfileRequest)(nil),                // 10: hub.v1.QueryProfileRequest
	(*QueryCortexNodeRequest)(nil),             // 11: hub.v1.QueryCortexNodeRequest
	(*QueryServiceBondRequest)(nil),            // 12: hub.v1.QueryServiceBondRequest
	(*QueryServiceUnbondingsRequest)(nil),      // 13: hub.v1.QueryServiceUnbondingsRequest
	(*QueryCurrentServiceKeyRequest)(nil),      // 14: hub.v1.QueryCurrentServiceKeyRequest
	(*QueryServiceDescriptorRequest)(nil),      // 15: hub.v1.QueryServiceDescriptorRequest
	(*QueryServiceLifecycleRequest)(nil),       // 16: hub.v1.QueryServiceLifecycleRequest
	(*QueryModelCapabilityRequest)(nil),        // 17: hub.v1.QueryModelCapabilityRequest
	(*QueryModelSupportRequest)(nil),           // 18: hub.v1.QueryModelSupportRequest
	(*QueryDailySupportRequest)(nil),           // 19: hub.v1.QueryDailySupportRequest
	(*QueryCurrentCandidatePoolRequest)(nil),   // 20: hub.v1.QueryCurrentCandidatePoolRequest
	(*QueryCandidatePoolSnapshotRequest)(nil),  // 21: hub.v1.QueryCandidatePoolSnapshotRequest
	(*QueryCandidatePoolMemberRequest)(nil),    // 22: hub.v1.QueryCandidatePoolMemberRequest
	(*QueryCandidatePoolMembersRequest)(nil),   // 23: hub.v1.QueryCandidatePoolMembersRequest
	(*QueryCompetitionEpochRequest)(nil),       // 24: hub.v1.QueryCompetitionEpochRequest
	(*QueryRewardEpochCursorRequest)(nil),      // 25: hub.v1.QueryRewardEpochCursorRequest
	(*QueryRewardEpochAuditRequest)(nil),       // 26: hub.v1.QueryRewardEpochAuditRequest
	(*QueryTreasuryRequest)(nil),               // 27: hub.v1.QueryTreasuryRequest
	(*QueryBridgeStatusRequest)(nil),           // 28: hub.v1.QueryBridgeStatusRequest
	(*QueryValidatorBridgeSignerRequest)(nil),  // 29: hub.v1.QueryValidatorBridgeSignerRequest
	(*QueryFreezeSignalRequest)(nil),           // 30: hub.v1.QueryFreezeSignalRequest
	(*QueryFreezeSignalsRequest)(nil),          // 31: hub.v1.QueryFreezeSignalsRequest
	(*QueryEmergencyFreezeVotesRequest)(nil),   // 32: hub.v1.QueryEmergencyFreezeVotesRequest
	(*QueryTimeoutBucketRequest)(nil),          // 33: hub.v1.QueryTimeoutBucketRequest
	(*QueryHubParamsResponse)(nil),             // 34: hub.v1.QueryHubParamsResponse
	(*QueryBeaconResponse)(nil),                // 35: hub.v1.QueryBeaconResponse
	(*QueryVrfKeyResponse)(nil),                // 36: hub.v1.QueryVrfKeyResponse
	(*QueryBuilderSetResponse)(nil),            // 37: hub.v1.QueryBuilderSetResponse
	(*QueryBuilderResponse)(nil),               // 38: hub.v1.QueryBuilderResponse
	(*QueryBuildersResponse)(nil),              // 39: hub.v1.QueryBuildersResponse
	(*QueryFaultResponse)(nil),                 // 40: hub.v1.QueryFaultResponse
	(*QueryEarningsResponse)(nil),              // 41: hub.v1.QueryEarningsResponse
	(*QueryModelResponse)(nil),                 // 42: hub.v1.QueryModelResponse
	(*QueryModelsResponse)(nil),                // 43: hub.v1.QueryModelsResponse
	(*QueryProfileResponse)(nil),               // 44: hub.v1.QueryProfileResponse
	(*QueryCortexNodeResponse)(nil),            // 45: hub.v1.QueryCortexNodeResponse
	(*QueryServiceBondResponse)(nil),           // 46: hub.v1.QueryServiceBondResponse
	(*QueryServiceUnbondingsResponse)(nil),     // 47: hub.v1.QueryServiceUnbondingsResponse
	(*QueryCurrentServiceKeyResponse)(nil),     // 48: hub.v1.QueryCurrentServiceKeyResponse
	(*QueryServiceDescriptorResponse)(nil),     // 49: hub.v1.QueryServiceDescriptorResponse
	(*QueryServiceLifecycleResponse)(nil),      // 50: hub.v1.QueryServiceLifecycleResponse
	(*QueryModelCapabilityResponse)(nil),       // 51: hub.v1.QueryModelCapabilityResponse
	(*QueryModelSupportResponse)(nil),          // 52: hub.v1.QueryModelSupportResponse
	(*QueryDailySupportResponse)(nil),          // 53: hub.v1.QueryDailySupportResponse
	(*QueryCurrentCandidatePoolResponse)(nil),  // 54: hub.v1.QueryCurrentCandidatePoolResponse
	(*QueryCandidatePoolSnapshotResponse)(nil), // 55: hub.v1.QueryCandidatePoolSnapshotResponse
	(*QueryCandidatePoolMemberResponse)(nil),   // 56: hub.v1.QueryCandidatePoolMemberResponse
	(*QueryCandidatePoolMembersResponse)(nil),  // 57: hub.v1.QueryCandidatePoolMembersResponse
	(*QueryCompetitionEpochResponse)(nil),      // 58: hub.v1.QueryCompetitionEpochResponse
	(*QueryRewardEpochCursorResponse)(nil),     // 59: hub.v1.QueryRewardEpochCursorResponse
	(*QueryRewardEpochAuditResponse)(nil),      // 60: hub.v1.QueryRewardEpochAuditResponse
	(*QueryTreasuryResponse)(nil),              // 61: hub.v1.QueryTreasuryResponse
	(*QueryBridgeStatusResponse)(nil),          // 62: hub.v1.QueryBridgeStatusResponse
	(*QueryValidatorBridgeSignerResponse)(nil), // 63: hub.v1.QueryValidatorBridgeSignerResponse
	(*QueryFreezeSignalResponse)(nil),          // 64: hub.v1.QueryFreezeSignalResponse
	(*QueryFreezeSignalsResponse)(nil),         // 65: hub.v1.QueryFreezeSignalsResponse
	(*QueryEmergencyFreezeVotesResponse)(nil),  // 66: hub.v1.QueryEmergencyFreezeVotesResponse
	(*QueryTimeoutBucketResponse)(nil),         // 67: hub.v1.QueryTimeoutBucketResponse
}
var file_hub_v1_query_proto_depIdxs = []int32{
	0,  // 0: hub.v1.Query.Params:input_type -> hub.v1.QueryHubParamsRequest
	1,  // 1: hub.v1.Query.Beacon:input_type -> hub.v1.QueryBeaconRequest
	2,  // 2: hub.v1.Query.VrfKey:input_type -> hub.v1.QueryVrfKeyRequest
	3,  // 3: hub.v1.Query.BuilderSet:input_type -> hub.v1.QueryBuilderSetRequest
	4,  // 4: hub.v1.Query.Builder:input_type -> hub.v1.QueryBuilderRequest
	5,  // 5: hub.v1.Query.Builders:input_type -> hub.v1.QueryBuildersRequest
	6,  // 6: hub.v1.Query.Fault:input_type -> hub.v1.QueryFaultRequest
	7,  // 7: hub.v1.Query.Earnings:input_type -> hub.v1.QueryEarningsRequest
	8,  // 8: hub.v1.Query.Model:input_type -> hub.v1.QueryModelRequest
	9,  // 9: hub.v1.Query.Models:input_type -> hub.v1.QueryModelsRequest
	10, // 10: hub.v1.Query.Profile:input_type -> hub.v1.QueryProfileRequest
	11, // 11: hub.v1.Query.CortexNode:input_type -> hub.v1.QueryCortexNodeRequest
	12, // 12: hub.v1.Query.ServiceBond:input_type -> hub.v1.QueryServiceBondRequest
	13, // 13: hub.v1.Query.ServiceUnbondings:input_type -> hub.v1.QueryServiceUnbondingsRequest
	14, // 14: hub.v1.Query.CurrentServiceKey:input_type -> hub.v1.QueryCurrentServiceKeyRequest
	15, // 15: hub.v1.Query.ServiceDescriptor:input_type -> hub.v1.QueryServiceDescriptorRequest
	16, // 16: hub.v1.Query.ServiceLifecycle:input_type -> hub.v1.QueryServiceLifecycleRequest
	17, // 17: hub.v1.Query.ModelCapability:input_type -> hub.v1.QueryModelCapabilityRequest
	18, // 18: hub.v1.Query.ModelSupport:input_type -> hub.v1.QueryModelSupportRequest
	19, // 19: hub.v1.Query.DailySupport:input_type -> hub.v1.QueryDailySupportRequest
	20, // 20: hub.v1.Query.CurrentCandidatePool:input_type -> hub.v1.QueryCurrentCandidatePoolRequest
	21, // 21: hub.v1.Query.CandidatePoolSnapshot:input_type -> hub.v1.QueryCandidatePoolSnapshotRequest
	22, // 22: hub.v1.Query.CandidatePoolMember:input_type -> hub.v1.QueryCandidatePoolMemberRequest
	23, // 23: hub.v1.Query.CandidatePoolMembers:input_type -> hub.v1.QueryCandidatePoolMembersRequest
	24, // 24: hub.v1.Query.CompetitionEpoch:input_type -> hub.v1.QueryCompetitionEpochRequest
	25, // 25: hub.v1.Query.RewardEpochCursor:input_type -> hub.v1.QueryRewardEpochCursorRequest
	26, // 26: hub.v1.Query.RewardEpochAudit:input_type -> hub.v1.QueryRewardEpochAuditRequest
	27, // 27: hub.v1.Query.Treasury:input_type -> hub.v1.QueryTreasuryRequest
	28, // 28: hub.v1.Query.BridgeStatus:input_type -> hub.v1.QueryBridgeStatusRequest
	29, // 29: hub.v1.Query.ValidatorBridgeSigner:input_type -> hub.v1.QueryValidatorBridgeSignerRequest
	30, // 30: hub.v1.Query.FreezeSignal:input_type -> hub.v1.QueryFreezeSignalRequest
	31, // 31: hub.v1.Query.FreezeSignals:input_type -> hub.v1.QueryFreezeSignalsRequest
	32, // 32: hub.v1.Query.EmergencyFreezeVotes:input_type -> hub.v1.QueryEmergencyFreezeVotesRequest
	33, // 33: hub.v1.Query.TimeoutBucket:input_type -> hub.v1.QueryTimeoutBucketRequest
	34, // 34: hub.v1.Query.Params:output_type -> hub.v1.QueryHubParamsResponse
	35, // 35: hub.v1.Query.Beacon:output_type -> hub.v1.QueryBeaconResponse
	36, // 36: hub.v1.Query.VrfKey:output_type -> hub.v1.QueryVrfKeyResponse
	37, // 37: hub.v1.Query.BuilderSet:output_type -> hub.v1.QueryBuilderSetResponse
	38, // 38: hub.v1.Query.Builder:output_type -> hub.v1.QueryBuilderResponse
	39, // 39: hub.v1.Query.Builders:output_type -> hub.v1.QueryBuildersResponse
	40, // 40: hub.v1.Query.Fault:output_type -> hub.v1.QueryFaultResponse
	41, // 41: hub.v1.Query.Earnings:output_type -> hub.v1.QueryEarningsResponse
	42, // 42: hub.v1.Query.Model:output_type -> hub.v1.QueryModelResponse
	43, // 43: hub.v1.Query.Models:output_type -> hub.v1.QueryModelsResponse
	44, // 44: hub.v1.Query.Profile:output_type -> hub.v1.QueryProfileResponse
	45, // 45: hub.v1.Query.CortexNode:output_type -> hub.v1.QueryCortexNodeResponse
	46, // 46: hub.v1.Query.ServiceBond:output_type -> hub.v1.QueryServiceBondResponse
	47, // 47: hub.v1.Query.ServiceUnbondings:output_type -> hub.v1.QueryServiceUnbondingsResponse
	48, // 48: hub.v1.Query.CurrentServiceKey:output_type -> hub.v1.QueryCurrentServiceKeyResponse
	49, // 49: hub.v1.Query.ServiceDescriptor:output_type -> hub.v1.QueryServiceDescriptorResponse
	50, // 50: hub.v1.Query.ServiceLifecycle:output_type -> hub.v1.QueryServiceLifecycleResponse
	51, // 51: hub.v1.Query.ModelCapability:output_type -> hub.v1.QueryModelCapabilityResponse
	52, // 52: hub.v1.Query.ModelSupport:output_type -> hub.v1.QueryModelSupportResponse
	53, // 53: hub.v1.Query.DailySupport:output_type -> hub.v1.QueryDailySupportResponse
	54, // 54: hub.v1.Query.CurrentCandidatePool:output_type -> hub.v1.QueryCurrentCandidatePoolResponse
	55, // 55: hub.v1.Query.CandidatePoolSnapshot:output_type -> hub.v1.QueryCandidatePoolSnapshotResponse
	56, // 56: hub.v1.Query.CandidatePoolMember:output_type -> hub.v1.QueryCandidatePoolMemberResponse
	57, // 57: hub.v1.Query.CandidatePoolMembers:output_type -> hub.v1.QueryCandidatePoolMembersResponse
	58, // 58: hub.v1.Query.CompetitionEpoch:output_type -> hub.v1.QueryCompetitionEpochResponse
	59, // 59: hub.v1.Query.RewardEpochCursor:output_type -> hub.v1.QueryRewardEpochCursorResponse
	60, // 60: hub.v1.Query.RewardEpochAudit:output_type -> hub.v1.QueryRewardEpochAuditResponse
	61, // 61: hub.v1.Query.Treasury:output_type -> hub.v1.QueryTreasuryResponse
	62, // 62: hub.v1.Query.BridgeStatus:output_type -> hub.v1.QueryBridgeStatusResponse
	63, // 63: hub.v1.Query.ValidatorBridgeSigner:output_type -> hub.v1.QueryValidatorBridgeSignerResponse
	64, // 64: hub.v1.Query.FreezeSignal:output_type -> hub.v1.QueryFreezeSignalResponse
	65, // 65: hub.v1.Query.FreezeSignals:output_type -> hub.v1.QueryFreezeSignalsResponse
	66, // 66: hub.v1.Query.EmergencyFreezeVotes:output_type -> hub.v1.QueryEmergencyFreezeVotesResponse
	67, // 67: hub.v1.Query.TimeoutBucket:output_type -> hub.v1.QueryTimeoutBucketResponse
	34, // [34:68] is the sub-list for method output_type
	0,  // [0:34] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hub_v1_query_proto_init() }
func file_hub_v1_query_proto_init() {
	if File_hub_v1_query_proto != nil {
		return
	}
	file_hub_v1_query_bridge_proto_init()
	file_hub_v1_query_registry_proto_init()
	file_hub_v1_query_rewards_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_query_proto_rawDesc), len(file_hub_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_query_proto_goTypes,
		DependencyIndexes: file_hub_v1_query_proto_depIdxs,
	}.Build()
	File_hub_v1_query_proto = out.File
	file_hub_v1_query_proto_goTypes = nil
	file_hub_v1_query_proto_depIdxs = nil
}
