// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: shared/v1/rest_encoding.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RESTBytesEncoding is the closed client projection registry for protobuf bytes
// leaves. The historical name is retained because the enum and extension are
// already frozen. There is no legacy "exactly 32 bytes means hex, otherwise
// Base64" category: every public service bytes leaf carries an explicit
// non-zero value.
// RESTBytesEncoding defines the RESTBytesEncoding wire type.
type RESTBytesEncoding int32

const (
	// Never valid on a public-service-reachable bytes leaf; the lint fails on it.
	// REST_BYTES_ENCODING_UNSPECIFIED identifies the corresponding protocol value.
	RESTBytesEncoding_REST_BYTES_ENCODING_UNSPECIFIED RESTBytesEncoding = 0
	// Ordinary variable-length bytes. Output is canonical RFC 4648
	// standard-alphabet Base64 with `=` padding. Input follows ProtoJSON and
	// accepts standard/URL-safe alphabets in padded and unpadded form (four
	// combinations), rejecting whitespace and malformed encodings. Typed
	// validation stays plain protobuf bytes and adds no length semantics.
	// REST_BYTES_ENCODING_PROTOJSON_BASE64 identifies the corresponding protocol value.
	RESTBytesEncoding_REST_BYTES_ENCODING_PROTOJSON_BASE64 RESTBytesEncoding = 1
	// A raw 32-byte digest/ID. Output is exactly 64 lowercase hex characters with
	// no `0x` prefix. Input accepts only that same form and is decoded to raw32
	// before typed validation; a present value must be exactly 32 raw bytes.
	// REST_BYTES_ENCODING_HASH32_LOWER_HEX identifies the corresponding protocol value.
	RESTBytesEncoding_REST_BYTES_ENCODING_HASH32_LOWER_HEX RESTBytesEncoding = 2
)

// Enum value maps for RESTBytesEncoding.
var (
	RESTBytesEncoding_name = map[int32]string{
		0: "REST_BYTES_ENCODING_UNSPECIFIED",
		1: "REST_BYTES_ENCODING_PROTOJSON_BASE64",
		2: "REST_BYTES_ENCODING_HASH32_LOWER_HEX",
	}
	RESTBytesEncoding_value = map[string]int32{
		"REST_BYTES_ENCODING_UNSPECIFIED":      0,
		"REST_BYTES_ENCODING_PROTOJSON_BASE64": 1,
		"REST_BYTES_ENCODING_HASH32_LOWER_HEX": 2,
	}
)

func (x RESTBytesEncoding) Enum() *RESTBytesEncoding {
	p := new(RESTBytesEncoding)
	*p = x
	return p
}

func (x RESTBytesEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RESTBytesEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_v1_rest_encoding_proto_enumTypes[0].Descriptor()
}

func (RESTBytesEncoding) Type() protoreflect.EnumType {
	return &file_shared_v1_rest_encoding_proto_enumTypes[0]
}

func (x RESTBytesEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RESTBytesEncoding.Descriptor instead.
func (RESTBytesEncoding) EnumDescriptor() ([]byte, []int) {
	return file_shared_v1_rest_encoding_proto_rawDescGZIP(), []int{0}
}

var file_shared_v1_rest_encoding_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*RESTBytesEncoding)(nil),
		Field:         51001,
		Name:          "shared.v1.rest_bytes_encoding",
		Tag:           "varint,51001,opt,name=rest_bytes_encoding,enum=shared.v1.RESTBytesEncoding",
		Filename:      "shared/v1/rest_encoding.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// rest_bytes_encoding declares the REST/JSON projection of one bytes leaf.
	// Extension number 51001 is frozen by this contract.
	//
	// optional shared.v1.RESTBytesEncoding rest_bytes_encoding = 51001;
	E_RestBytesEncoding = &file_shared_v1_rest_encoding_proto_extTypes[0]
)

var File_shared_v1_rest_encoding_proto protoreflect.FileDescriptor

const file_shared_v1_rest_encoding_proto_rawDesc = "" +
	"\n" +
	"\x1dshared/v1/rest_encoding.proto\x12\tshared.v1\x1a google/protobuf/descriptor.proto*\x8c\x01\n" +
	"\x11RESTBytesEncoding\x12#\n" +
	"\x1fREST_BYTES_ENCODING_UNSPECIFIED\x10\x00\x12(\n" +
	"$REST_BYTES_ENCODING_PROTOJSON_BASE64\x10\x01\x12(\n" +
	"$REST_BYTES_ENCODING_HASH32_LOWER_HEX\x10\x02:m\n" +
	"\x13rest_bytes_encoding\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\x0e2\x1c.shared.v1.RESTBytesEncodingR\x11restBytesEncodingB)Z'github.com/TrueOpen/node/x/shared/typesb\x06proto3"

var (
	file_shared_v1_rest_encoding_proto_rawDescOnce sync.Once
	file_shared_v1_rest_encoding_proto_rawDescData []byte
)

func file_shared_v1_rest_encoding_proto_rawDescGZIP() []byte {
	file_shared_v1_rest_encoding_proto_rawDescOnce.Do(func() {
		file_shared_v1_rest_encoding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_v1_rest_encoding_proto_rawDesc), len(file_shared_v1_rest_encoding_proto_rawDesc)))
	})
	return file_shared_v1_rest_encoding_proto_rawDescData
}

var file_shared_v1_rest_encoding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_v1_rest_encoding_proto_goTypes = []any{
	(RESTBytesEncoding)(0),            // 0: shared.v1.RESTBytesEncoding
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_shared_v1_rest_encoding_proto_depIdxs = []int32{
	1, // 0: shared.v1.rest_bytes_encoding:extendee -> google.protobuf.FieldOptions
	0, // 1: shared.v1.rest_bytes_encoding:type_name -> shared.v1.RESTBytesEncoding
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_v1_rest_encoding_proto_init() }
func file_shared_v1_rest_encoding_proto_init() {
	if File_shared_v1_rest_encoding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_v1_rest_encoding_proto_rawDesc), len(file_shared_v1_rest_encoding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_shared_v1_rest_encoding_proto_goTypes,
		DependencyIndexes: file_shared_v1_rest_encoding_proto_depIdxs,
		EnumInfos:         file_shared_v1_rest_encoding_proto_enumTypes,
		ExtensionInfos:    file_shared_v1_rest_encoding_proto_extTypes,
	}.Build()
	File_shared_v1_rest_encoding_proto = out.File
	file_shared_v1_rest_encoding_proto_goTypes = nil
	file_shared_v1_rest_encoding_proto_depIdxs = nil
}
