// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: task/v1/query.proto

package types

import (
	_ "github.com/SingaXYZ/cortex/proto/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_task_v1_query_proto protoreflect.FileDescriptor

const file_task_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x13task/v1/query.proto\x12\atask.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btask/v1/query_session.proto\x1a$task/v1/query_settlement_build.proto\x1a\x18task/v1/query_task.proto2\xf9\"\n" +
	"\x05Query\x12m\n" +
	"\x06Params\x12\x1f.task.v1.QueryTaskParamsRequest\x1a .task.v1.QueryTaskParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/TrueOpen/task/v1/params\x12g\n" +
	"\x04Task\x12\x19.task.v1.QueryTaskRequest\x1a\x1a.task.v1.QueryTaskResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /TrueOpen/task/v1/task/{task_id}\x12|\n" +
	"\tTaskStage\x12\x1e.task.v1.QueryTaskStageRequest\x1a\x1f.task.v1.QueryTaskStageResponse\".\x82\xd3\xe4\x93\x02(\x12&/TrueOpen/task/v1/task/{task_id}/stage\x12\x90\x01\n" +
	"\x0eTaskAssignment\x12#.task.v1.QueryTaskAssignmentRequest\x1a$.task.v1.QueryTaskAssignmentResponse\"3\x82\xd3\xe4\x93\x02-\x12+/TrueOpen/task/v1/task/{task_id}/assignment\x12\xad\x01\n" +
	"\x14AssignmentRandomness\x12).task.v1.QueryAssignmentRandomnessRequest\x1a*.task.v1.QueryAssignmentRandomnessResponse\">\x82\xd3\xe4\x93\x028\x126/TrueOpen/task/v1/task/{task_id}/assignment_randomness\x12\x80\x01\n" +
	"\n" +
	"TaskBudget\x12\x1f.task.v1.QueryTaskBudgetRequest\x1a .task.v1.QueryTaskBudgetResponse\"/\x82\xd3\xe4\x93\x02)\x12'/TrueOpen/task/v1/task/{task_id}/budget\x12\x88\x01\n" +
	"\fTaskBuilders\x12!.task.v1.QueryTaskBuildersRequest\x1a\".task.v1.QueryTaskBuildersResponse\"1\x82\xd3\xe4\x93\x02+\x12)/TrueOpen/task/v1/task/{task_id}/builders\x12\x8d\x01\n" +
	"\fInferReceipt\x12!.task.v1.QueryInferReceiptRequest\x1a\".task.v1.QueryInferReceiptResponse\"6\x82\xd3\xe4\x93\x020\x12./TrueOpen/task/v1/task/{task_id}/infer_receipt\x12\xb5\x01\n" +
	"\x0eWorkerEvidence\x12#.task.v1.QueryWorkerEvidenceRequest\x1a$.task.v1.QueryWorkerEvidenceResponse\"X\x82\xd3\xe4\x93\x02R\x12P/TrueOpen/task/v1/task/{task_id}/worker_evidence/{worker_operator_address}/{seq}\x12\xbf\x01\n" +
	"\x17VerifierCandidateWindow\x12,.task.v1.QueryVerifierCandidateWindowRequest\x1a-.task.v1.QueryVerifierCandidateWindowResponse\"G\x82\xd3\xe4\x93\x02A\x12?/TrueOpen/task/v1/task/{task_id}/verifier_window/{verify_round}\x12\xb4\x01\n" +
	"\x12VerifierAssignment\x12'.task.v1.QueryVerifierAssignmentRequest\x1a(.task.v1.QueryVerifierAssignmentResponse\"K\x82\xd3\xe4\x93\x02E\x12C/TrueOpen/task/v1/task/{task_id}/verifier_assignment/{verify_round}\x12\xb1\x01\n" +
	"\fVerifyCommit\x12!.task.v1.QueryVerifyCommitRequest\x1a\".task.v1.QueryVerifyCommitResponse\"Z\x82\xd3\xe4\x93\x02T\x12R/TrueOpen/task/v1/task/{task_id}/commit/{verify_round}/{verifier_operator_address}\x12\xbc\x01\n" +
	"\rResultReceipt\x12\".task.v1.QueryResultReceiptRequest\x1a#.task.v1.QueryResultReceiptResponse\"b\x82\xd3\xe4\x93\x02\\\x12Z/TrueOpen/task/v1/task/{task_id}/result_receipt/{verify_round}/{verifier_operator_address}\x12\xc5\x01\n" +
	"\x16DataUnavailableReports\x12+.task.v1.QueryDataUnavailableReportsRequest\x1a,.task.v1.QueryDataUnavailableReportsResponse\"P\x82\xd3\xe4\x93\x02J\x12H/TrueOpen/task/v1/task/{task_id}/data_unavailable_reports/{verify_round}\x12\xe0\x01\n" +
	"\x16BuilderDataUnavailable\x12+.task.v1.QueryBuilderDataUnavailableRequest\x1a,.task.v1.QueryBuilderDataUnavailableResponse\"k\x82\xd3\xe4\x93\x02e\x12c/TrueOpen/task/v1/task/{task_id}/builder_data_unavailable/{verify_round}/{builder_operator_address}\x12\x99\x01\n" +
	"\x0fSettlementFacts\x12$.task.v1.QuerySettlementFactsRequest\x1a%.task.v1.QuerySettlementFactsResponse\"9\x82\xd3\xe4\x93\x023\x121/TrueOpen/task/v1/task/{task_id}/settlement_facts\x12\x84\x01\n" +
	"\n" +
	"Settlement\x12\x1f.task.v1.QuerySettlementRequest\x1a .task.v1.QuerySettlementResponse\"3\x82\xd3\xe4\x93\x02-\x12+/TrueOpen/task/v1/task/{task_id}/settlement\x12\xb0\x01\n" +
	"\x11VerificationRound\x12&.task.v1.QueryVerificationRoundRequest\x1a'.task.v1.QueryVerificationRoundResponse\"J\x82\xd3\xe4\x93\x02D\x12B/TrueOpen/task/v1/task/{task_id}/verification_round/{verify_round}\x12\xad\x01\n" +
	"\x15TaskGasReimbursements\x12*.task.v1.QueryTaskGasReimbursementsRequest\x1a+.task.v1.QueryTaskGasReimbursementsResponse\";\x82\xd3\xe4\x93\x025\x123/TrueOpen/task/v1/task/{task_id}/gas_reimbursements\x12\x99\x01\n" +
	"\x10TaskFailureClass\x12%.task.v1.QueryTaskFailureClassRequest\x1a&.task.v1.QueryTaskFailureClassResponse\"6\x82\xd3\xe4\x93\x020\x12./TrueOpen/task/v1/task/{task_id}/failure_class\x12\x90\x01\n" +
	"\x0fEvidenceCleanup\x12$.task.v1.QueryEvidenceCleanupRequest\x1a%.task.v1.QueryEvidenceCleanupResponse\"0\x82\xd3\xe4\x93\x02*\x12(/TrueOpen/task/v1/task/{task_id}/cleanup\x12\x97\x01\n" +
	"\x10EpochTaskSummary\x12%.task.v1.QueryEpochTaskSummaryRequest\x1a&.task.v1.QueryEpochTaskSummaryResponse\"4\x82\xd3\xe4\x93\x02.\x12,/TrueOpen/task/v1/epoch/{epoch}/task_summary\x12v\n" +
	"\aSession\x12\x1c.task.v1.QuerySessionRequest\x1a\x1d.task.v1.QuerySessionResponse\".\x82\xd3\xe4\x93\x02(\x12&/TrueOpen/task/v1/session/{session_id}\x12\x8d\x01\n" +
	"\fSessionNonce\x12!.task.v1.QuerySessionNonceRequest\x1a\".task.v1.QuerySessionNonceResponse\"6\x82\xd3\xe4\x93\x020\x12./TrueOpen/task/v1/session_nonce/{user_address}\x12\x91\x01\n" +
	"\x0fSessionsByOwner\x12$.task.v1.QuerySessionsByOwnerRequest\x1a%.task.v1.QuerySessionsByOwnerResponse\"1\x82\xd3\xe4\x93\x02+\x12)/TrueOpen/task/v1/sessions/{user_address}\x12\xb4\x01\n" +
	"\x16SessionTerminalSummary\x12+.task.v1.QuerySessionTerminalSummaryRequest\x1a,.task.v1.QuerySessionTerminalSummaryResponse\"?\x82\xd3\xe4\x93\x029\x127/TrueOpen/task/v1/session/{session_id}/terminal_summary\x12\x9f\x01\n" +
	"\rOrderSequence\x12\".task.v1.QueryOrderSequenceRequest\x1a#.task.v1.QueryOrderSequenceResponse\"E\x82\xd3\xe4\x93\x02?\x12=/TrueOpen/task/v1/session/{session_id}/order/{order_sequence}\x12\xa5\x01\n" +
	"\x0fRoleActiveTasks\x12$.task.v1.QueryRoleActiveTasksRequest\x1a%.task.v1.QueryRoleActiveTasksResponse\"E\x82\xd3\xe4\x93\x02?\x12=/TrueOpen/task/v1/role/{operator_address}/{duty}/active_tasksB'Z%github.com/TrueOpen/node/x/task/typesb\x06proto3"

var file_task_v1_query_proto_goTypes = []any{
	(*QueryTaskParamsRequest)(nil),               // 0: task.v1.QueryTaskParamsRequest
	(*QueryTaskRequest)(nil),                     // 1: task.v1.QueryTaskRequest
	(*QueryTaskStageRequest)(nil),                // 2: task.v1.QueryTaskStageRequest
	(*QueryTaskAssignmentRequest)(nil),           // 3: task.v1.QueryTaskAssignmentRequest
	(*QueryAssignmentRandomnessRequest)(nil),     // 4: task.v1.QueryAssignmentRandomnessRequest
	(*QueryTaskBudgetRequest)(nil),               // 5: task.v1.QueryTaskBudgetRequest
	(*QueryTaskBuildersRequest)(nil),             // 6: task.v1.QueryTaskBuildersRequest
	(*QueryInferReceiptRequest)(nil),             // 7: task.v1.QueryInferReceiptRequest
	(*QueryWorkerEvidenceRequest)(nil),           // 8: task.v1.QueryWorkerEvidenceRequest
	(*QueryVerifierCandidateWindowRequest)(nil),  // 9: task.v1.QueryVerifierCandidateWindowRequest
	(*QueryVerifierAssignmentRequest)(nil),       // 10: task.v1.QueryVerifierAssignmentRequest
	(*QueryVerifyCommitRequest)(nil),             // 11: task.v1.QueryVerifyCommitRequest
	(*QueryResultReceiptRequest)(nil),            // 12: task.v1.QueryResultReceiptRequest
	(*QueryDataUnavailableReportsRequest)(nil),   // 13: task.v1.QueryDataUnavailableReportsRequest
	(*QueryBuilderDataUnavailableRequest)(nil),   // 14: task.v1.QueryBuilderDataUnavailableRequest
	(*QuerySettlementFactsRequest)(nil),          // 15: task.v1.QuerySettlementFactsRequest
	(*QuerySettlementRequest)(nil),               // 16: task.v1.QuerySettlementRequest
	(*QueryVerificationRoundRequest)(nil),        // 17: task.v1.QueryVerificationRoundRequest
	(*QueryTaskGasReimbursementsRequest)(nil),    // 18: task.v1.QueryTaskGasReimbursementsRequest
	(*QueryTaskFailureClassRequest)(nil),         // 19: task.v1.QueryTaskFailureClassRequest
	(*QueryEvidenceCleanupRequest)(nil),          // 20: task.v1.QueryEvidenceCleanupRequest
	(*QueryEpochTaskSummaryRequest)(nil),         // 21: task.v1.QueryEpochTaskSummaryRequest
	(*QuerySessionRequest)(nil),                  // 22: task.v1.QuerySessionRequest
	(*QuerySessionNonceRequest)(nil),             // 23: task.v1.QuerySessionNonceRequest
	(*QuerySessionsByOwnerRequest)(nil),          // 24: task.v1.QuerySessionsByOwnerRequest
	(*QuerySessionTerminalSummaryRequest)(nil),   // 25: task.v1.QuerySessionTerminalSummaryRequest
	(*QueryOrderSequenceRequest)(nil),            // 26: task.v1.QueryOrderSequenceRequest
	(*QueryRoleActiveTasksRequest)(nil),          // 27: task.v1.QueryRoleActiveTasksRequest
	(*QueryTaskParamsResponse)(nil),              // 28: task.v1.QueryTaskParamsResponse
	(*QueryTaskResponse)(nil),                    // 29: task.v1.QueryTaskResponse
	(*QueryTaskStageResponse)(nil),               // 30: task.v1.QueryTaskStageResponse
	(*QueryTaskAssignmentResponse)(nil),          // 31: task.v1.QueryTaskAssignmentResponse
	(*QueryAssignmentRandomnessResponse)(nil),    // 32: task.v1.QueryAssignmentRandomnessResponse
	(*QueryTaskBudgetResponse)(nil),              // 33: task.v1.QueryTaskBudgetResponse
	(*QueryTaskBuildersResponse)(nil),            // 34: task.v1.QueryTaskBuildersResponse
	(*QueryInferReceiptResponse)(nil),            // 35: task.v1.QueryInferReceiptResponse
	(*QueryWorkerEvidenceResponse)(nil),          // 36: task.v1.QueryWorkerEvidenceResponse
	(*QueryVerifierCandidateWindowResponse)(nil), // 37: task.v1.QueryVerifierCandidateWindowResponse
	(*QueryVerifierAssignmentResponse)(nil),      // 38: task.v1.QueryVerifierAssignmentResponse
	(*QueryVerifyCommitResponse)(nil),            // 39: task.v1.QueryVerifyCommitResponse
	(*QueryResultReceiptResponse)(nil),           // 40: task.v1.QueryResultReceiptResponse
	(*QueryDataUnavailableReportsResponse)(nil),  // 41: task.v1.QueryDataUnavailableReportsResponse
	(*QueryBuilderDataUnavailableResponse)(nil),  // 42: task.v1.QueryBuilderDataUnavailableResponse
	(*QuerySettlementFactsResponse)(nil),         // 43: task.v1.QuerySettlementFactsResponse
	(*QuerySettlementResponse)(nil),              // 44: task.v1.QuerySettlementResponse
	(*QueryVerificationRoundResponse)(nil),       // 45: task.v1.QueryVerificationRoundResponse
	(*QueryTaskGasReimbursementsResponse)(nil),   // 46: task.v1.QueryTaskGasReimbursementsResponse
	(*QueryTaskFailureClassResponse)(nil),        // 47: task.v1.QueryTaskFailureClassResponse
	(*QueryEvidenceCleanupResponse)(nil),         // 48: task.v1.QueryEvidenceCleanupResponse
	(*QueryEpochTaskSummaryResponse)(nil),        // 49: task.v1.QueryEpochTaskSummaryResponse
	(*QuerySessionResponse)(nil),                 // 50: task.v1.QuerySessionResponse
	(*QuerySessionNonceResponse)(nil),            // 51: task.v1.QuerySessionNonceResponse
	(*QuerySessionsByOwnerResponse)(nil),         // 52: task.v1.QuerySessionsByOwnerResponse
	(*QuerySessionTerminalSummaryResponse)(nil),  // 53: task.v1.QuerySessionTerminalSummaryResponse
	(*QueryOrderSequenceResponse)(nil),           // 54: task.v1.QueryOrderSequenceResponse
	(*QueryRoleActiveTasksResponse)(nil),         // 55: task.v1.QueryRoleActiveTasksResponse
}
var file_task_v1_query_proto_depIdxs = []int32{
	0,  // 0: task.v1.Query.Params:input_type -> task.v1.QueryTaskParamsRequest
	1,  // 1: task.v1.Query.Task:input_type -> task.v1.QueryTaskRequest
	2,  // 2: task.v1.Query.TaskStage:input_type -> task.v1.QueryTaskStageRequest
	3,  // 3: task.v1.Query.TaskAssignment:input_type -> task.v1.QueryTaskAssignmentRequest
	4,  // 4: task.v1.Query.AssignmentRandomness:input_type -> task.v1.QueryAssignmentRandomnessRequest
	5,  // 5: task.v1.Query.TaskBudget:input_type -> task.v1.QueryTaskBudgetRequest
	6,  // 6: task.v1.Query.TaskBuilders:input_type -> task.v1.QueryTaskBuildersRequest
	7,  // 7: task.v1.Query.InferReceipt:input_type -> task.v1.QueryInferReceiptRequest
	8,  // 8: task.v1.Query.WorkerEvidence:input_type -> task.v1.QueryWorkerEvidenceRequest
	9,  // 9: task.v1.Query.VerifierCandidateWindow:input_type -> task.v1.QueryVerifierCandidateWindowRequest
	10, // 10: task.v1.Query.VerifierAssignment:input_type -> task.v1.QueryVerifierAssignmentRequest
	11, // 11: task.v1.Query.VerifyCommit:input_type -> task.v1.QueryVerifyCommitRequest
	12, // 12: task.v1.Query.ResultReceipt:input_type -> task.v1.QueryResultReceiptRequest
	13, // 13: task.v1.Query.DataUnavailableReports:input_type -> task.v1.QueryDataUnavailableReportsRequest
	14, // 14: task.v1.Query.BuilderDataUnavailable:input_type -> task.v1.QueryBuilderDataUnavailableRequest
	15, // 15: task.v1.Query.SettlementFacts:input_type -> task.v1.QuerySettlementFactsRequest
	16, // 16: task.v1.Query.Settlement:input_type -> task.v1.QuerySettlementRequest
	17, // 17: task.v1.Query.VerificationRound:input_type -> task.v1.QueryVerificationRoundRequest
	18, // 18: task.v1.Query.TaskGasReimbursements:input_type -> task.v1.QueryTaskGasReimbursementsRequest
	19, // 19: task.v1.Query.TaskFailureClass:input_type -> task.v1.QueryTaskFailureClassRequest
	20, // 20: task.v1.Query.EvidenceCleanup:input_type -> task.v1.QueryEvidenceCleanupRequest
	21, // 21: task.v1.Query.EpochTaskSummary:input_type -> task.v1.QueryEpochTaskSummaryRequest
	22, // 22: task.v1.Query.Session:input_type -> task.v1.QuerySessionRequest
	23, // 23: task.v1.Query.SessionNonce:input_type -> task.v1.QuerySessionNonceRequest
	24, // 24: task.v1.Query.SessionsByOwner:input_type -> task.v1.QuerySessionsByOwnerRequest
	25, // 25: task.v1.Query.SessionTerminalSummary:input_type -> task.v1.QuerySessionTerminalSummaryRequest
	26, // 26: task.v1.Query.OrderSequence:input_type -> task.v1.QueryOrderSequenceRequest
	27, // 27: task.v1.Query.RoleActiveTasks:input_type -> task.v1.QueryRoleActiveTasksRequest
	28, // 28: task.v1.Query.Params:output_type -> task.v1.QueryTaskParamsResponse
	29, // 29: task.v1.Query.Task:output_type -> task.v1.QueryTaskResponse
	30, // 30: task.v1.Query.TaskStage:output_type -> task.v1.QueryTaskStageResponse
	31, // 31: task.v1.Query.TaskAssignment:output_type -> task.v1.QueryTaskAssignmentResponse
	32, // 32: task.v1.Query.AssignmentRandomness:output_type -> task.v1.QueryAssignmentRandomnessResponse
	33, // 33: task.v1.Query.TaskBudget:output_type -> task.v1.QueryTaskBudgetResponse
	34, // 34: task.v1.Query.TaskBuilders:output_type -> task.v1.QueryTaskBuildersResponse
	35, // 35: task.v1.Query.InferReceipt:output_type -> task.v1.QueryInferReceiptResponse
	36, // 36: task.v1.Query.WorkerEvidence:output_type -> task.v1.QueryWorkerEvidenceResponse
	37, // 37: task.v1.Query.VerifierCandidateWindow:output_type -> task.v1.QueryVerifierCandidateWindowResponse
	38, // 38: task.v1.Query.VerifierAssignment:output_type -> task.v1.QueryVerifierAssignmentResponse
	39, // 39: task.v1.Query.VerifyCommit:output_type -> task.v1.QueryVerifyCommitResponse
	40, // 40: task.v1.Query.ResultReceipt:output_type -> task.v1.QueryResultReceiptResponse
	41, // 41: task.v1.Query.DataUnavailableReports:output_type -> task.v1.QueryDataUnavailableReportsResponse
	42, // 42: task.v1.Query.BuilderDataUnavailable:output_type -> task.v1.QueryBuilderDataUnavailableResponse
	43, // 43: task.v1.Query.SettlementFacts:output_type -> task.v1.QuerySettlementFactsResponse
	44, // 44: task.v1.Query.Settlement:output_type -> task.v1.QuerySettlementResponse
	45, // 45: task.v1.Query.VerificationRound:output_type -> task.v1.QueryVerificationRoundResponse
	46, // 46: task.v1.Query.TaskGasReimbursements:output_type -> task.v1.QueryTaskGasReimbursementsResponse
	47, // 47: task.v1.Query.TaskFailureClass:output_type -> task.v1.QueryTaskFailureClassResponse
	48, // 48: task.v1.Query.EvidenceCleanup:output_type -> task.v1.QueryEvidenceCleanupResponse
	49, // 49: task.v1.Query.EpochTaskSummary:output_type -> task.v1.QueryEpochTaskSummaryResponse
	50, // 50: task.v1.Query.Session:output_type -> task.v1.QuerySessionResponse
	51, // 51: task.v1.Query.SessionNonce:output_type -> task.v1.QuerySessionNonceResponse
	52, // 52: task.v1.Query.SessionsByOwner:output_type -> task.v1.QuerySessionsByOwnerResponse
	53, // 53: task.v1.Query.SessionTerminalSummary:output_type -> task.v1.QuerySessionTerminalSummaryResponse
	54, // 54: task.v1.Query.OrderSequence:output_type -> task.v1.QueryOrderSequenceResponse
	55, // 55: task.v1.Query.RoleActiveTasks:output_type -> task.v1.QueryRoleActiveTasksResponse
	28, // [28:56] is the sub-list for method output_type
	0,  // [0:28] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_task_v1_query_proto_init() }
func file_task_v1_query_proto_init() {
	if File_task_v1_query_proto != nil {
		return
	}
	file_task_v1_query_session_proto_init()
	file_task_v1_query_settlement_build_proto_init()
	file_task_v1_query_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_query_proto_rawDesc), len(file_task_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_v1_query_proto_goTypes,
		DependencyIndexes: file_task_v1_query_proto_depIdxs,
	}.Build()
	File_task_v1_query_proto = out.File
	file_task_v1_query_proto_goTypes = nil
	file_task_v1_query_proto_depIdxs = nil
}
