// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: task/v1/query_session.proto

package types

import (
	_ "github.com/TrueOpen/cortex/proto/amino"
	_ "github.com/TrueOpen/cortex/proto/cosmos_proto"
	_ "github.com/TrueOpen/cortex/proto/gogoproto"
	v1 "github.com/TrueOpen/cortex/proto/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryTaskParamsRequest is request type for Query/Params.
//
// The parameter query belongs to the params domain. It
// is kept unchanged so query.proto keeps resolving; the wire API requires a
// single `QueryParams` returning `1=hub_params:HubParamsV1,2=task_params:TaskParamsV1`.
// QueryTaskParamsRequest defines the QueryTaskParamsRequest wire type.
type QueryTaskParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskParamsRequest) Reset() {
	*x = QueryTaskParamsRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskParamsRequest) ProtoMessage() {}

func (x *QueryTaskParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryTaskParamsRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{0}
}

// QueryTaskParamsResponse is response type for the Query/Params RPC method.
type QueryTaskParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params holds all the parameters of this module.
	Params *TaskParamsV1 `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// meta carries this module's own params version/hash/updated height. Params
	// ownership stays per module: a client that needs a joint view calls
	// hub.v1.Query/Params and task.v1.Query/Params at the same
	// x-cosmos-block-height. Wire adds no app-level package importing both.
	Meta          *TaskParamsMetaState `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTaskParamsResponse) Reset() {
	*x = QueryTaskParamsResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTaskParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTaskParamsResponse) ProtoMessage() {}

func (x *QueryTaskParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTaskParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryTaskParamsResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{1}
}

func (x *QueryTaskParamsResponse) GetParams() *TaskParamsV1 {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryTaskParamsResponse) GetMeta() *TaskParamsMetaState {
	if x != nil {
		return x.Meta
	}
	return nil
}

// QuerySessionRequest selects one session by ID.
type QuerySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionRequest) Reset() {
	*x = QuerySessionRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionRequest) ProtoMessage() {}

func (x *QuerySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionRequest.ProtoReflect.Descriptor instead.
func (*QuerySessionRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{2}
}

func (x *QuerySessionRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// QuerySessionResponse returns the authoritative StreamState for an
// active/idle/closed retained row; after compaction the RPC returns NotFound and
// callers must query the terminal summary instead.
// QuerySessionResponse defines the QuerySessionResponse wire type.
type QuerySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *StreamState           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionResponse) Reset() {
	*x = QuerySessionResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionResponse) ProtoMessage() {}

func (x *QuerySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionResponse.ProtoReflect.Descriptor instead.
func (*QuerySessionResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{3}
}

func (x *QuerySessionResponse) GetSession() *StreamState {
	if x != nil {
		return x.Session
	}
	return nil
}

// QuerySessionsByOwnerRequest lists the owner's active sessions.
type QuerySessionsByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAddress   string                 `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	Page          *v1.QueryPageRequestV1 `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionsByOwnerRequest) Reset() {
	*x = QuerySessionsByOwnerRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionsByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionsByOwnerRequest) ProtoMessage() {}

func (x *QuerySessionsByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionsByOwnerRequest.ProtoReflect.Descriptor instead.
func (*QuerySessionsByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySessionsByOwnerRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *QuerySessionsByOwnerRequest) GetPage() *v1.QueryPageRequestV1 {
	if x != nil {
		return x.Page
	}
	return nil
}

// QuerySessionsByOwnerResponse walks only the active owner index, ascending by
// raw session_id bytes; closed history is never listed permanently.
// QuerySessionsByOwnerResponse defines the QuerySessionsByOwnerResponse wire type.
type QuerySessionsByOwnerResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*StreamState          `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Page          *v1.QueryPageResponseV1 `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionsByOwnerResponse) Reset() {
	*x = QuerySessionsByOwnerResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionsByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionsByOwnerResponse) ProtoMessage() {}

func (x *QuerySessionsByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionsByOwnerResponse.ProtoReflect.Descriptor instead.
func (*QuerySessionsByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySessionsByOwnerResponse) GetSessions() []*StreamState {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *QuerySessionsByOwnerResponse) GetPage() *v1.QueryPageResponseV1 {
	if x != nil {
		return x.Page
	}
	return nil
}

// QuerySessionTerminalSummaryRequest selects one collapsed session.
type QuerySessionTerminalSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionTerminalSummaryRequest) Reset() {
	*x = QuerySessionTerminalSummaryRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionTerminalSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionTerminalSummaryRequest) ProtoMessage() {}

func (x *QuerySessionTerminalSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionTerminalSummaryRequest.ProtoReflect.Descriptor instead.
func (*QuerySessionTerminalSummaryRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{6}
}

func (x *QuerySessionTerminalSummaryRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// QuerySessionTerminalSummaryResponse returns the single terminal summary;
// NotFound after its retention expires.
// QuerySessionTerminalSummaryResponse defines the QuerySessionTerminalSummaryResponse wire type.
type QuerySessionTerminalSummaryResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Summary       *SessionTerminalSummaryState `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionTerminalSummaryResponse) Reset() {
	*x = QuerySessionTerminalSummaryResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionTerminalSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionTerminalSummaryResponse) ProtoMessage() {}

func (x *QuerySessionTerminalSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionTerminalSummaryResponse.ProtoReflect.Descriptor instead.
func (*QuerySessionTerminalSummaryResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{7}
}

func (x *QuerySessionTerminalSummaryResponse) GetSummary() *SessionTerminalSummaryState {
	if x != nil {
		return x.Summary
	}
	return nil
}

// QuerySessionNonceRequest selects one user's session counter.
type QuerySessionNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAddress   string                 `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySessionNonceRequest) Reset() {
	*x = QuerySessionNonceRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionNonceRequest) ProtoMessage() {}

func (x *QuerySessionNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionNonceRequest.ProtoReflect.Descriptor instead.
func (*QuerySessionNonceRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{8}
}

func (x *QuerySessionNonceRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

// QuerySessionNonceResponse returns 0 for an account with no session yet; an
// invalid address is InvalidArgument, never empty state.
// QuerySessionNonceResponse defines the QuerySessionNonceResponse wire type.
type QuerySessionNonceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NextSessionNonce uint64                 `protobuf:"varint,1,opt,name=next_session_nonce,json=nextSessionNonce,proto3" json:"next_session_nonce,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuerySessionNonceResponse) Reset() {
	*x = QuerySessionNonceResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySessionNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySessionNonceResponse) ProtoMessage() {}

func (x *QuerySessionNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySessionNonceResponse.ProtoReflect.Descriptor instead.
func (*QuerySessionNonceResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{9}
}

func (x *QuerySessionNonceResponse) GetNextSessionNonce() uint64 {
	if x != nil {
		return x.NextSessionNonce
	}
	return 0
}

// QueryOrderSequenceRequest selects one order sequence row.
type QueryOrderSequenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrderSequence uint64                 `protobuf:"varint,2,opt,name=order_sequence,json=orderSequence,proto3" json:"order_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderSequenceRequest) Reset() {
	*x = QueryOrderSequenceRequest{}
	mi := &file_task_v1_query_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderSequenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderSequenceRequest) ProtoMessage() {}

func (x *QueryOrderSequenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderSequenceRequest.ProtoReflect.Descriptor instead.
func (*QueryOrderSequenceRequest) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{10}
}

func (x *QueryOrderSequenceRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *QueryOrderSequenceRequest) GetOrderSequence() uint64 {
	if x != nil {
		return x.OrderSequence
	}
	return 0
}

// QueryOrderSequenceResponse returns the row only inside the detail retention
// window; NotFound once it has been folded into sequence_root, which defines no
// member proof.
// QueryOrderSequenceResponse defines the QueryOrderSequenceResponse wire type.
type QueryOrderSequenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      *OrderSequenceState    `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOrderSequenceResponse) Reset() {
	*x = QueryOrderSequenceResponse{}
	mi := &file_task_v1_query_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOrderSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderSequenceResponse) ProtoMessage() {}

func (x *QueryOrderSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_query_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderSequenceResponse.ProtoReflect.Descriptor instead.
func (*QueryOrderSequenceResponse) Descriptor() ([]byte, []int) {
	return file_task_v1_query_session_proto_rawDescGZIP(), []int{11}
}

func (x *QueryOrderSequenceResponse) GetSequence() *OrderSequenceState {
	if x != nil {
		return x.Sequence
	}
	return nil
}

var File_task_v1_query_session_proto protoreflect.FileDescriptor

const file_task_v1_query_session_proto_rawDesc = "" +
	"\n" +
	"\x1btask/v1/query_session.proto\x12\atask.v1\x1a\x11amino/amino.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1ashared/v1/query_page.proto\x1a\x1dshared/v1/rest_encoding.proto\x1a\x14task/v1/params.proto\x1a\x15task/v1/session.proto\"\x18\n" +
	"\x16QueryTaskParamsRequest\"\x90\x01\n" +
	"\x17QueryTaskParamsResponse\x128\n" +
	"\x06params\x18\x01 \x01(\v2\x15.task.v1.TaskParamsV1B\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12;\n" +
	"\x04meta\x18\x02 \x01(\v2\x1c.task.v1.TaskParamsMetaStateB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x04meta\":\n" +
	"\x13QuerySessionRequest\x12#\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fB\x04\xc8\xf3\x18\x02R\tsessionId\"L\n" +
	"\x14QuerySessionResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x14.task.v1.StreamStateB\x04\xc8\xde\x1f\x00R\asession\"\x93\x01\n" +
	"\x1bQuerySessionsByOwnerRequest\x12;\n" +
	"\fuser_address\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\vuserAddress\x127\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.shared.v1.QueryPageRequestV1B\x04\xc8\xde\x1f\x00R\x04page\"\x90\x01\n" +
	"\x1cQuerySessionsByOwnerResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.task.v1.StreamStateB\x04\xc8\xde\x1f\x00R\bsessions\x128\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.shared.v1.QueryPageResponseV1B\x04\xc8\xde\x1f\x00R\x04page\"I\n" +
	"\"QuerySessionTerminalSummaryRequest\x12#\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fB\x04\xc8\xf3\x18\x02R\tsessionId\"k\n" +
	"#QuerySessionTerminalSummaryResponse\x12D\n" +
	"\asummary\x18\x01 \x01(\v2$.task.v1.SessionTerminalSummaryStateB\x04\xc8\xde\x1f\x00R\asummary\"W\n" +
	"\x18QuerySessionNonceRequest\x12;\n" +
	"\fuser_address\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\vuserAddress\"I\n" +
	"\x19QuerySessionNonceResponse\x12,\n" +
	"\x12next_session_nonce\x18\x01 \x01(\x04R\x10nextSessionNonce\"g\n" +
	"\x19QueryOrderSequenceRequest\x12#\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fB\x04\xc8\xf3\x18\x02R\tsessionId\x12%\n" +
	"\x0eorder_sequence\x18\x02 \x01(\x04R\rorderSequence\"[\n" +
	"\x1aQueryOrderSequenceResponse\x12=\n" +
	"\bsequence\x18\x01 \x01(\v2\x1b.task.v1.OrderSequenceStateB\x04\xc8\xde\x1f\x00R\bsequenceB'Z%github.com/TrueOpen/node/x/task/typesb\x06proto3"

var (
	file_task_v1_query_session_proto_rawDescOnce sync.Once
	file_task_v1_query_session_proto_rawDescData []byte
)

func file_task_v1_query_session_proto_rawDescGZIP() []byte {
	file_task_v1_query_session_proto_rawDescOnce.Do(func() {
		file_task_v1_query_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_query_session_proto_rawDesc), len(file_task_v1_query_session_proto_rawDesc)))
	})
	return file_task_v1_query_session_proto_rawDescData
}

var file_task_v1_query_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_task_v1_query_session_proto_goTypes = []any{
	(*QueryTaskParamsRequest)(nil),              // 0: task.v1.QueryTaskParamsRequest
	(*QueryTaskParamsResponse)(nil),             // 1: task.v1.QueryTaskParamsResponse
	(*QuerySessionRequest)(nil),                 // 2: task.v1.QuerySessionRequest
	(*QuerySessionResponse)(nil),                // 3: task.v1.QuerySessionResponse
	(*QuerySessionsByOwnerRequest)(nil),         // 4: task.v1.QuerySessionsByOwnerRequest
	(*QuerySessionsByOwnerResponse)(nil),        // 5: task.v1.QuerySessionsByOwnerResponse
	(*QuerySessionTerminalSummaryRequest)(nil),  // 6: task.v1.QuerySessionTerminalSummaryRequest
	(*QuerySessionTerminalSummaryResponse)(nil), // 7: task.v1.QuerySessionTerminalSummaryResponse
	(*QuerySessionNonceRequest)(nil),            // 8: task.v1.QuerySessionNonceRequest
	(*QuerySessionNonceResponse)(nil),           // 9: task.v1.QuerySessionNonceResponse
	(*QueryOrderSequenceRequest)(nil),           // 10: task.v1.QueryOrderSequenceRequest
	(*QueryOrderSequenceResponse)(nil),          // 11: task.v1.QueryOrderSequenceResponse
	(*TaskParamsV1)(nil),                        // 12: task.v1.TaskParamsV1
	(*TaskParamsMetaState)(nil),                 // 13: task.v1.TaskParamsMetaState
	(*StreamState)(nil),                         // 14: task.v1.StreamState
	(*v1.QueryPageRequestV1)(nil),               // 15: shared.v1.QueryPageRequestV1
	(*v1.QueryPageResponseV1)(nil),              // 16: shared.v1.QueryPageResponseV1
	(*SessionTerminalSummaryState)(nil),         // 17: task.v1.SessionTerminalSummaryState
	(*OrderSequenceState)(nil),                  // 18: task.v1.OrderSequenceState
}
var file_task_v1_query_session_proto_depIdxs = []int32{
	12, // 0: task.v1.QueryTaskParamsResponse.params:type_name -> task.v1.TaskParamsV1
	13, // 1: task.v1.QueryTaskParamsResponse.meta:type_name -> task.v1.TaskParamsMetaState
	14, // 2: task.v1.QuerySessionResponse.session:type_name -> task.v1.StreamState
	15, // 3: task.v1.QuerySessionsByOwnerRequest.page:type_name -> shared.v1.QueryPageRequestV1
	14, // 4: task.v1.QuerySessionsByOwnerResponse.sessions:type_name -> task.v1.StreamState
	16, // 5: task.v1.QuerySessionsByOwnerResponse.page:type_name -> shared.v1.QueryPageResponseV1
	17, // 6: task.v1.QuerySessionTerminalSummaryResponse.summary:type_name -> task.v1.SessionTerminalSummaryState
	18, // 7: task.v1.QueryOrderSequenceResponse.sequence:type_name -> task.v1.OrderSequenceState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_task_v1_query_session_proto_init() }
func file_task_v1_query_session_proto_init() {
	if File_task_v1_query_session_proto != nil {
		return
	}
	file_task_v1_params_proto_init()
	file_task_v1_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_query_session_proto_rawDesc), len(file_task_v1_query_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_v1_query_session_proto_goTypes,
		DependencyIndexes: file_task_v1_query_session_proto_depIdxs,
		MessageInfos:      file_task_v1_query_session_proto_msgTypes,
	}.Build()
	File_task_v1_query_session_proto = out.File
	file_task_v1_query_session_proto_goTypes = nil
	file_task_v1_query_session_proto_depIdxs = nil
}
