// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cosmos/msg/v1/msg.proto

package msgservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_cosmos_msg_v1_msg_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         11110000,
		Name:          "cosmos.msg.v1.service",
		Tag:           "varint,11110000,opt,name=service",
		Filename:      "cosmos/msg/v1/msg.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         11110000,
		Name:          "cosmos.msg.v1.signer",
		Tag:           "bytes,11110000,rep,name=signer",
		Filename:      "cosmos/msg/v1/msg.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// service indicates that the service is a Msg service and that requests
	// must be transported via blockchain transactions rather than gRPC.
	// Tooling can use this annotation to distinguish between Msg services and
	// other types of services via reflection.
	//
	// optional bool service = 11110000;
	E_Service = &file_cosmos_msg_v1_msg_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// signer must be used in cosmos messages in order
	// to signal to external clients which fields in a
	// given cosmos message must be filled with signer
	// information (address).
	// The field must be the protobuf name of the message
	// field extended with this MessageOption.
	// The field must either be of string kind, or of message
	// kind in case the signer information is contained within
	// a message inside the cosmos message.
	//
	// repeated string signer = 11110000;
	E_Signer = &file_cosmos_msg_v1_msg_proto_extTypes[1]
)

var File_cosmos_msg_v1_msg_proto protoreflect.FileDescriptor

const file_cosmos_msg_v1_msg_proto_rawDesc = "" +
	"\n" +
	"\x17cosmos/msg/v1/msg.proto\x12\rcosmos.msg.v1\x1a google/protobuf/descriptor.proto:<\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xf0\x8c\xa6\x05 \x01(\bR\aservice::\n" +
	"\x06signer\x12\x1f.google.protobuf.MessageOptions\x18\xf0\x8c\xa6\x05 \x03(\tR\x06signerB/Z-github.com/cosmos/cosmos-sdk/types/msgserviceb\x06proto3"

var file_cosmos_msg_v1_msg_proto_goTypes = []any{
	(*descriptorpb.ServiceOptions)(nil), // 0: google.protobuf.ServiceOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_cosmos_msg_v1_msg_proto_depIdxs = []int32{
	0, // 0: cosmos.msg.v1.service:extendee -> google.protobuf.ServiceOptions
	1, // 1: cosmos.msg.v1.signer:extendee -> google.protobuf.MessageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_msg_v1_msg_proto_init() }
func file_cosmos_msg_v1_msg_proto_init() {
	if File_cosmos_msg_v1_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosmos_msg_v1_msg_proto_rawDesc), len(file_cosmos_msg_v1_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_msg_v1_msg_proto_goTypes,
		DependencyIndexes: file_cosmos_msg_v1_msg_proto_depIdxs,
		ExtensionInfos:    file_cosmos_msg_v1_msg_proto_extTypes,
	}.Build()
	File_cosmos_msg_v1_msg_proto = out.File
	file_cosmos_msg_v1_msg_proto_goTypes = nil
	file_cosmos_msg_v1_msg_proto_depIdxs = nil
}
