// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: amino/amino.proto

package amino

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_amino_amino_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         11110001,
		Name:          "amino.name",
		Tag:           "bytes,11110001,opt,name=name",
		Filename:      "amino/amino.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         11110002,
		Name:          "amino.message_encoding",
		Tag:           "bytes,11110002,opt,name=message_encoding",
		Filename:      "amino/amino.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         11110003,
		Name:          "amino.encoding",
		Tag:           "bytes,11110003,opt,name=encoding",
		Filename:      "amino/amino.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         11110004,
		Name:          "amino.field_name",
		Tag:           "bytes,11110004,opt,name=field_name",
		Filename:      "amino/amino.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         11110005,
		Name:          "amino.dont_omitempty",
		Tag:           "varint,11110005,opt,name=dont_omitempty",
		Filename:      "amino/amino.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         11110006,
		Name:          "amino.oneof_name",
		Tag:           "bytes,11110006,opt,name=oneof_name",
		Filename:      "amino/amino.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// name is the string used when registering a concrete
	// type into the Amino type registry, via the Amino codec's
	// `RegisterConcrete()` method. This string MUST be at most 39
	// characters long, or else the message will be rejected by the
	// Ledger hardware device.
	//
	// optional string name = 11110001;
	E_Name = &file_amino_amino_proto_extTypes[0]
	// encoding describes the encoding format used by Amino for the given
	// message. The field type is chosen to be a string for
	// flexibility, but it should ideally be short and expected to be
	// machine-readable, for example "base64" or "utf8_json". We
	// highly recommend to use underscores for word separation instead of spaces.
	//
	// If left empty, then the Amino encoding is expected to be the same as the
	// Protobuf one.
	//
	// This annotation should not be confused with the `encoding`
	// one which operates on the field level.
	//
	// optional string message_encoding = 11110002;
	E_MessageEncoding = &file_amino_amino_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// encoding describes the encoding format used by Amino for
	// the given field. The field type is chosen to be a string for
	// flexibility, but it should ideally be short and expected to be
	// machine-readable, for example "base64" or "utf8_json". We
	// highly recommend to use underscores for word separation instead of spaces.
	//
	// If left empty, then the Amino encoding is expected to be the same as the
	// Protobuf one.
	//
	// This annotation should not be confused with the
	// `message_encoding` one which operates on the message level.
	//
	// optional string encoding = 11110003;
	E_Encoding = &file_amino_amino_proto_extTypes[2]
	// field_name sets a different field name (i.e. key name) in
	// the amino JSON object for the given field.
	//
	// Example:
	//
	//	message Foo {
	//	  string bar = 1 [(amino.field_name) = "baz"];
	//	}
	//
	// Then the Amino encoding of Foo will be:
	// `{"baz":"some value"}`
	//
	// optional string field_name = 11110004;
	E_FieldName = &file_amino_amino_proto_extTypes[3]
	// dont_omitempty sets the field in the JSON object even if
	// its value is empty, i.e. equal to the Golang zero value. To learn what
	// the zero values are, see https://go.dev/ref/spec#The_zero_value.
	//
	// Fields default to `omitempty`, which is the default behavior when this
	// annotation is unset. When set to true, then the field value in the
	// JSON object will be set, i.e. not `undefined`.
	//
	// Example:
	//
	//	message Foo {
	//	  string bar = 1;
	//	  string baz = 2 [(amino.dont_omitempty) = true];
	//	}
	//
	// f := Foo{};
	// out := AminoJSONEncoder(&f);
	// out == {"baz":""}
	//
	// optional bool dont_omitempty = 11110005;
	E_DontOmitempty = &file_amino_amino_proto_extTypes[4]
	// oneof_name sets the type name for the given field oneof field.  This is used
	// by the Amino JSON encoder to encode the type of the oneof field, and must be the same string in
	// the RegisterConcrete() method usage used to register the concrete type.
	//
	// optional string oneof_name = 11110006;
	E_OneofName = &file_amino_amino_proto_extTypes[5]
)

var File_amino_amino_proto protoreflect.FileDescriptor

const file_amino_amino_proto_rawDesc = "" +
	"\n" +
	"\x11amino/amino.proto\x12\x05amino\x1a google/protobuf/descriptor.proto:6\n" +
	"\x04name\x12\x1f.google.protobuf.MessageOptions\x18\xf1\x8c\xa6\x05 \x01(\tR\x04name:M\n" +
	"\x10message_encoding\x12\x1f.google.protobuf.MessageOptions\x18\xf2\x8c\xa6\x05 \x01(\tR\x0fmessageEncoding:<\n" +
	"\bencoding\x12\x1d.google.protobuf.FieldOptions\x18\xf3\x8c\xa6\x05 \x01(\tR\bencoding:?\n" +
	"\n" +
	"field_name\x12\x1d.google.protobuf.FieldOptions\x18\xf4\x8c\xa6\x05 \x01(\tR\tfieldName:G\n" +
	"\x0edont_omitempty\x12\x1d.google.protobuf.FieldOptions\x18\xf5\x8c\xa6\x05 \x01(\bR\rdontOmitempty:?\n" +
	"\n" +
	"oneof_name\x12\x1d.google.protobuf.FieldOptions\x18\xf6\x8c\xa6\x05 \x01(\tR\toneofNameB-Z+github.com/cosmos/cosmos-sdk/types/tx/aminob\x06proto3"

var file_amino_amino_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_amino_amino_proto_depIdxs = []int32{
	0, // 0: amino.name:extendee -> google.protobuf.MessageOptions
	0, // 1: amino.message_encoding:extendee -> google.protobuf.MessageOptions
	1, // 2: amino.encoding:extendee -> google.protobuf.FieldOptions
	1, // 3: amino.field_name:extendee -> google.protobuf.FieldOptions
	1, // 4: amino.dont_omitempty:extendee -> google.protobuf.FieldOptions
	1, // 5: amino.oneof_name:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amino_amino_proto_init() }
func file_amino_amino_proto_init() {
	if File_amino_amino_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amino_amino_proto_rawDesc), len(file_amino_amino_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_amino_amino_proto_goTypes,
		DependencyIndexes: file_amino_amino_proto_depIdxs,
		ExtensionInfos:    file_amino_amino_proto_extTypes,
	}.Build()
	File_amino_amino_proto = out.File
	file_amino_amino_proto_goTypes = nil
	file_amino_amino_proto_depIdxs = nil
}
