package chainclient

import (
	"sort"
	"strings"
	"testing"
)

// chainTaskEventNames is every event message name node defines in
// x/task/types/event.pb.go that really appears in a block (with the
// task.v1 prefix omitted).
//
// cortex does not import the chain's event proto, so this list is a hand-synchronised
// mirror; when node adds or removes an event this test fails and asks for a sync. The
// list itself is generated by
//
//	grep -oE "^type Event[A-Za-z]+ struct" node/x/task/types/event.pb.go
var chainTaskEventNames = []string{
	"EventAssignmentFailed",
	"EventBuilderDataUnavailable",
	"EventCommitAccepted",
	"EventCommitDeadlineClosed",
	"EventDataUnavailableReported",
	"EventDeadlineSwept",
	"EventChallengeRoundOpened",
	"EventVerificationRoundClosed",
	"EventTaskGasReimbursementRecorded",
	"EventInferReceiptAccepted",
	"EventOrderCancelled",
	"EventResultAccepted",
	"EventRevealPhaseStarted",
	"EventSessionCreated",
	"EventTaskFailureClassUpdated",
	"EventTaskParamsUpdated",
	"EventTaskSettled",
	"EventVerifierAssignmentFinalized",
	"EventVerifierHandraisesAccepted",
	"EventVerifyOpenTimeout",
	"EventWorkerAssignmentFinalized",
	"EventWorkerEvidenceAccepted",
	"EventWorkerHandraisesAccepted",
	"EventWorkerTimeout",
}

// pendingOnChain holds event names cortex reserves ahead of the chain, which the chain
// does not define yet (node has not implemented the challenge and evidence-request
// paths). They never appear in a block, so they are not silent breakage; once node
// implements them they should move from here into chainTaskEventNames.
var pendingOnChain = map[string]bool{
	"task.v1.EventChallengeClosed":                   true,
	"task.v1.EventChallengeCommitAccepted":           true,
	"task.v1.EventChallengeEconomicEffectApplied":    true,
	"task.v1.EventChallengeFullResultRevealAccepted": true,
	"task.v1.EventChallengeLivenessIssueRecorded":    true,
	"task.v1.EventChallengeOpened":                   true,
	"task.v1.EventChallengeOutcomeRecorded":          true,
	"task.v1.EventChallengeResultAccepted":           true,
	"task.v1.EventChallengeSampleSeedReady":          true,
	"task.v1.EventEvidenceCleanup":                   true,
	"task.v1.EventEvidenceCleanupDeferred":           true,
	"task.v1.EventEvidenceRequestDefaulted":          true,
	"task.v1.EventEvidenceRequestSatisfied":          true,
	"task.v1.EventEvidenceRequested":                 true,
	"task.v1.EventFaultReportDispatched":             true,
	"task.v1.EventRevealDeadlineClosed":              true,
	"task.v1.EventSettleAccepted":                    true,
	"task.v1.EventTaskEvidenceRootRecorded":          true,
	"task.v1.EventTaskFinalityAdvanced":              true,
	"task.v1.EventVerificationSampleSeedReady":       true,
	"task.v1.EventVerifyOpenDeadlineClosed":          true,
	"task.v1.EventWorkerRevealAccepted":              true,
	"task.v1.EventWorkerRevealDeadlineClosed":        true,
}

// TestABCIEventNamesExistOnChain pins the event-name mapping table against the real
// on-chain event names.
//
// The keys of that table are the fully qualified message names of Cosmos typed events.
// When a name does not match, the event is silently skipped as an unknown type - no
// error, no quarantine, no log line - and the pipeline stalls without a sound. In
// local integration this presented as "the chain says the assignment is final while
// cortex keeps saying it cannot find one locally", which was extremely expensive to
// diagnose, so any name in the table that does not exist on chain fails outright.
func TestABCIEventNamesExistOnChain(t *testing.T) {
	onChain := make(map[string]bool, len(chainTaskEventNames))
	for _, name := range chainTaskEventNames {
		onChain["task.v1."+name] = true
	}

	var unknown []string
	for name := range keeperABCIEventTypes {
		if !strings.HasPrefix(name, "task.v1.") {
			continue // events of other modules are out of scope for this list
		}
		if pendingOnChain[name] {
			continue
		}
		if !onChain[name] {
			unknown = append(unknown, name)
		}
	}
	sort.Strings(unknown)
	if len(unknown) > 0 {
		t.Fatalf("these event names do not exist on chain and are silently skipped at run time:\n  %s",
			strings.Join(unknown, "\n  "))
	}
}

// TestFlowCriticalEventsAreMapped pins the events required to advance the task
// lifecycle. Missing any one of them leaves a task stuck at the matching stage
// without reporting an error.
func TestFlowCriticalEventsAreMapped(t *testing.T) {
	for _, name := range []string{
		"task.v1.EventWorkerHandraisesAccepted",
		"task.v1.EventWorkerAssignmentFinalized",
		"task.v1.EventInferReceiptAccepted",
		"task.v1.EventVerifierAssignmentFinalized",
		"task.v1.EventCommitAccepted",
		"task.v1.EventResultAccepted",
		"task.v1.EventTaskSettled",
	} {
		if _, ok := keeperABCIEventTypes[name]; !ok {
			t.Errorf("lifecycle-critical event not mapped: %s", name)
		}
	}
}
