// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cosmos/base/v1beta1/coin.proto

package types

import (
	_ "github.com/TrueOpen/cortex/proto/amino"
	_ "github.com/TrueOpen/cortex/proto/cosmos_proto"
	_ "github.com/TrueOpen/cortex/proto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Coin defines a token with a denomination and an amount.
//
// NOTE: The amount field is an Int which implements the custom method
// signatures required by gogoproto.
type Coin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coin) Reset() {
	*x = Coin{}
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coin) ProtoMessage() {}

func (x *Coin) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coin.ProtoReflect.Descriptor instead.
func (*Coin) Descriptor() ([]byte, []int) {
	return file_cosmos_base_v1beta1_coin_proto_rawDescGZIP(), []int{0}
}

func (x *Coin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Coin) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// DecCoin defines a token with a denomination and a decimal amount.
//
// NOTE: The amount field is a Dec which implements the custom method
// signatures required by gogoproto.
type DecCoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecCoin) Reset() {
	*x = DecCoin{}
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecCoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecCoin) ProtoMessage() {}

func (x *DecCoin) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecCoin.ProtoReflect.Descriptor instead.
func (*DecCoin) Descriptor() ([]byte, []int) {
	return file_cosmos_base_v1beta1_coin_proto_rawDescGZIP(), []int{1}
}

func (x *DecCoin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *DecCoin) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// IntProto defines a Protobuf wrapper around an Int object.
// Deprecated: Prefer to use math.Int directly. It supports binary Marshal and Unmarshal.
type IntProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int           string                 `protobuf:"bytes,1,opt,name=int,proto3" json:"int,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntProto) Reset() {
	*x = IntProto{}
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntProto) ProtoMessage() {}

func (x *IntProto) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntProto.ProtoReflect.Descriptor instead.
func (*IntProto) Descriptor() ([]byte, []int) {
	return file_cosmos_base_v1beta1_coin_proto_rawDescGZIP(), []int{2}
}

func (x *IntProto) GetInt() string {
	if x != nil {
		return x.Int
	}
	return ""
}

// DecProto defines a Protobuf wrapper around a Dec object.
// Deprecated: Prefer to use math.LegacyDec directly. It supports binary Marshal and Unmarshal.
type DecProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dec           string                 `protobuf:"bytes,1,opt,name=dec,proto3" json:"dec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecProto) Reset() {
	*x = DecProto{}
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecProto) ProtoMessage() {}

func (x *DecProto) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_base_v1beta1_coin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecProto.ProtoReflect.Descriptor instead.
func (*DecProto) Descriptor() ([]byte, []int) {
	return file_cosmos_base_v1beta1_coin_proto_rawDescGZIP(), []int{3}
}

func (x *DecProto) GetDec() string {
	if x != nil {
		return x.Dec
	}
	return ""
}

var File_cosmos_base_v1beta1_coin_proto protoreflect.FileDescriptor

const file_cosmos_base_v1beta1_coin_proto_rawDesc = "" +
	"\n" +
	"\x1ecosmos/base/v1beta1/coin.proto\x12\x13cosmos.base.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x11amino/amino.proto\"l\n" +
	"\x04Coin\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12H\n" +
	"\x06amount\x18\x02 \x01(\tB0\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntҴ-\n" +
	"cosmos.Int\xa8\xe7\xb0*\x01R\x06amount:\x04\xe8\xa0\x1f\x01\"p\n" +
	"\aDecCoin\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12I\n" +
	"\x06amount\x18\x02 \x01(\tB1\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecҴ-\n" +
	"cosmos.DecR\x06amount:\x04\xe8\xa0\x1f\x01\"I\n" +
	"\bIntProto\x12=\n" +
	"\x03int\x18\x01 \x01(\tB+\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntҴ-\n" +
	"cosmos.IntR\x03int\"O\n" +
	"\bDecProto\x12C\n" +
	"\x03dec\x18\x01 \x01(\tB1\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecҴ-\n" +
	"cosmos.DecR\x03decB,\xd8\xe1\x1e\x00\x80\xe2\x1e\x00Z\"github.com/cosmos/cosmos-sdk/typesb\x06proto3"

var (
	file_cosmos_base_v1beta1_coin_proto_rawDescOnce sync.Once
	file_cosmos_base_v1beta1_coin_proto_rawDescData []byte
)

func file_cosmos_base_v1beta1_coin_proto_rawDescGZIP() []byte {
	file_cosmos_base_v1beta1_coin_proto_rawDescOnce.Do(func() {
		file_cosmos_base_v1beta1_coin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosmos_base_v1beta1_coin_proto_rawDesc), len(file_cosmos_base_v1beta1_coin_proto_rawDesc)))
	})
	return file_cosmos_base_v1beta1_coin_proto_rawDescData
}

var file_cosmos_base_v1beta1_coin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cosmos_base_v1beta1_coin_proto_goTypes = []any{
	(*Coin)(nil),     // 0: cosmos.base.v1beta1.Coin
	(*DecCoin)(nil),  // 1: cosmos.base.v1beta1.DecCoin
	(*IntProto)(nil), // 2: cosmos.base.v1beta1.IntProto
	(*DecProto)(nil), // 3: cosmos.base.v1beta1.DecProto
}
var file_cosmos_base_v1beta1_coin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_base_v1beta1_coin_proto_init() }
func file_cosmos_base_v1beta1_coin_proto_init() {
	if File_cosmos_base_v1beta1_coin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosmos_base_v1beta1_coin_proto_rawDesc), len(file_cosmos_base_v1beta1_coin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_base_v1beta1_coin_proto_goTypes,
		DependencyIndexes: file_cosmos_base_v1beta1_coin_proto_depIdxs,
		MessageInfos:      file_cosmos_base_v1beta1_coin_proto_msgTypes,
	}.Build()
	File_cosmos_base_v1beta1_coin_proto = out.File
	file_cosmos_base_v1beta1_coin_proto_goTypes = nil
	file_cosmos_base_v1beta1_coin_proto_depIdxs = nil
}
