// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cortex/v1/chat_output.proto

package cortexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NOTE (current implementation): the chat capability NO LONGER delivers this
// ChatCompletion object. The committed/delivered output is now the RAW TEXT decoded
// from the committed token_ids -- each generated token's bytes
// (logprobs.content[i].bytes) concatenated in order, including the trailing EOS
// special token -- exactly like the raw-text (inferV0) path, so the delivered text,
// the streamed chunk text, trace.Output and checkpoint.Output all correspond
// byte-for-byte to the token_ids the Verifier scores. tool_calls are not parsed out
// separately; any tool-call syntax the model emitted is just tokens in that raw
// text. This message is retained for reference only and is no longer the delivered
// shape (no Go code constructs or parses it).
//
// ChatCompletionOutput was the committed output the chat capability delivered: a
// clean OpenAI Chat Completions RESPONSE object (verified against openai-python
// v1.107.3).
//
// It carries only the fields an OpenAI ChatCompletion requires to validate
// (id, object, created, model, choices) plus usage (commonly read for metering).
// Every vLLM-internal field is deliberately EXCLUDED -- token_ids, logprobs and
// especially prompt_token_ids are evidence material, not user output, and the
// last would leak the chat-template-expanded input tokens.
//
// finish_reason here is the FAITHFUL model value ("tool_calls", "stop", ...) --
// distinct from the in-set FinishReasonV1 the worker-value commitment binds
// (where "tool_calls" maps to EOS). The two serve different purposes.
type ChatCompletionOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique id for the completion (passed through from the engine).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// object is always "chat.completion".
	Object string `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// created is the Unix timestamp (seconds) of when the completion was produced.
	Created int64 `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	// model is the chain model_id the task ran under (protocol identity).
	Model   string                        `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices []*ChatCompletionOutputChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	// usage is optional but recommended; clients read it for metering.
	Usage         *ChatCompletionOutputUsage `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionOutput) Reset() {
	*x = ChatCompletionOutput{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionOutput) ProtoMessage() {}

func (x *ChatCompletionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionOutput.ProtoReflect.Descriptor instead.
func (*ChatCompletionOutput) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{0}
}

func (x *ChatCompletionOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionOutput) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionOutput) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionOutput) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionOutput) GetChoices() []*ChatCompletionOutputChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionOutput) GetUsage() *ChatCompletionOutputUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// ChatCompletionOutputChoice is one completion candidate. The single-sample
// model means there is exactly one, at index 0: more than one candidate cannot
// be verified, which is why the request rejects OpenAI's n.
type ChatCompletionOutputChoice struct {
	state   protoimpl.MessageState       `protogen:"open.v1"`
	Index   int32                        `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message *ChatCompletionOutputMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// finish_reason is the faithful model value: "stop" | "length" | "tool_calls"
	// | "content_filter" | "function_call".
	FinishReason  string `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionOutputChoice) Reset() {
	*x = ChatCompletionOutputChoice{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionOutputChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionOutputChoice) ProtoMessage() {}

func (x *ChatCompletionOutputChoice) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionOutputChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionOutputChoice) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletionOutputChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionOutputChoice) GetMessage() *ChatCompletionOutputMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletionOutputChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// ChatCompletionOutputMessage is the assistant turn the model produced.
type ChatCompletionOutputMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role is always "assistant".
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// content is the assistant text; empty when the turn only carried tool_calls.
	Content       string            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*OutputToolCall `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionOutputMessage) Reset() {
	*x = ChatCompletionOutputMessage{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionOutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionOutputMessage) ProtoMessage() {}

func (x *ChatCompletionOutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionOutputMessage.ProtoReflect.Descriptor instead.
func (*ChatCompletionOutputMessage) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{2}
}

func (x *ChatCompletionOutputMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatCompletionOutputMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatCompletionOutputMessage) GetToolCalls() []*OutputToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

// OutputToolCall is one tool invocation the model emitted. Under the current
// implementation nothing parses these out of the committed text, so this shape
// describes what a consumer may derive, not what the protocol delivers.
type OutputToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is "function".
	Type          string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *OutputFunctionCall `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputToolCall) Reset() {
	*x = OutputToolCall{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputToolCall) ProtoMessage() {}

func (x *OutputToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputToolCall.ProtoReflect.Descriptor instead.
func (*OutputToolCall) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{3}
}

func (x *OutputToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutputToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputToolCall) GetFunction() *OutputFunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

// OutputFunctionCall names the called function and its arguments.
type OutputFunctionCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// arguments is the model-generated arguments as a JSON string (OpenAI wire
	// shape); it may not be valid JSON and must be validated before use.
	Arguments     string `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputFunctionCall) Reset() {
	*x = OutputFunctionCall{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFunctionCall) ProtoMessage() {}

func (x *OutputFunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFunctionCall.ProtoReflect.Descriptor instead.
func (*OutputFunctionCall) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{4}
}

func (x *OutputFunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutputFunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// ChatCompletionOutputUsage is the token accounting clients read for metering.
// It is reported, not committed: the protocol's own accounting comes from the
// generated token count in the receipt.
type ChatCompletionOutputUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatCompletionOutputUsage) Reset() {
	*x = ChatCompletionOutputUsage{}
	mi := &file_cortex_v1_chat_output_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionOutputUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionOutputUsage) ProtoMessage() {}

func (x *ChatCompletionOutputUsage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_output_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionOutputUsage.ProtoReflect.Descriptor instead.
func (*ChatCompletionOutputUsage) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_output_proto_rawDescGZIP(), []int{5}
}

func (x *ChatCompletionOutputUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatCompletionOutputUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ChatCompletionOutputUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_cortex_v1_chat_output_proto protoreflect.FileDescriptor

const file_cortex_v1_chat_output_proto_rawDesc = "" +
	"\n" +
	"\x1bcortex/v1/chat_output.proto\x12\tcortex.v1\"\xeb\x01\n" +
	"\x14ChatCompletionOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12?\n" +
	"\achoices\x18\x05 \x03(\v2%.cortex.v1.ChatCompletionOutputChoiceR\achoices\x12:\n" +
	"\x05usage\x18\x06 \x01(\v2$.cortex.v1.ChatCompletionOutputUsageR\x05usage\"\x99\x01\n" +
	"\x1aChatCompletionOutputChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12@\n" +
	"\amessage\x18\x02 \x01(\v2&.cortex.v1.ChatCompletionOutputMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\x85\x01\n" +
	"\x1bChatCompletionOutputMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x19.cortex.v1.OutputToolCallR\ttoolCalls\"o\n" +
	"\x0eOutputToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x129\n" +
	"\bfunction\x18\x03 \x01(\v2\x1d.cortex.v1.OutputFunctionCallR\bfunction\"F\n" +
	"\x12OutputFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"\x90\x01\n" +
	"\x19ChatCompletionOutputUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokensB1Z/github.com/TrueOpen/wire/gen/cortex/v1;cortexv1b\x06proto3"

var (
	file_cortex_v1_chat_output_proto_rawDescOnce sync.Once
	file_cortex_v1_chat_output_proto_rawDescData []byte
)

func file_cortex_v1_chat_output_proto_rawDescGZIP() []byte {
	file_cortex_v1_chat_output_proto_rawDescOnce.Do(func() {
		file_cortex_v1_chat_output_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_v1_chat_output_proto_rawDesc), len(file_cortex_v1_chat_output_proto_rawDesc)))
	})
	return file_cortex_v1_chat_output_proto_rawDescData
}

var file_cortex_v1_chat_output_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cortex_v1_chat_output_proto_goTypes = []any{
	(*ChatCompletionOutput)(nil),        // 0: cortex.v1.ChatCompletionOutput
	(*ChatCompletionOutputChoice)(nil),  // 1: cortex.v1.ChatCompletionOutputChoice
	(*ChatCompletionOutputMessage)(nil), // 2: cortex.v1.ChatCompletionOutputMessage
	(*OutputToolCall)(nil),              // 3: cortex.v1.OutputToolCall
	(*OutputFunctionCall)(nil),          // 4: cortex.v1.OutputFunctionCall
	(*ChatCompletionOutputUsage)(nil),   // 5: cortex.v1.ChatCompletionOutputUsage
}
var file_cortex_v1_chat_output_proto_depIdxs = []int32{
	1, // 0: cortex.v1.ChatCompletionOutput.choices:type_name -> cortex.v1.ChatCompletionOutputChoice
	5, // 1: cortex.v1.ChatCompletionOutput.usage:type_name -> cortex.v1.ChatCompletionOutputUsage
	2, // 2: cortex.v1.ChatCompletionOutputChoice.message:type_name -> cortex.v1.ChatCompletionOutputMessage
	3, // 3: cortex.v1.ChatCompletionOutputMessage.tool_calls:type_name -> cortex.v1.OutputToolCall
	4, // 4: cortex.v1.OutputToolCall.function:type_name -> cortex.v1.OutputFunctionCall
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cortex_v1_chat_output_proto_init() }
func file_cortex_v1_chat_output_proto_init() {
	if File_cortex_v1_chat_output_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_v1_chat_output_proto_rawDesc), len(file_cortex_v1_chat_output_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cortex_v1_chat_output_proto_goTypes,
		DependencyIndexes: file_cortex_v1_chat_output_proto_depIdxs,
		MessageInfos:      file_cortex_v1_chat_output_proto_msgTypes,
	}.Build()
	File_cortex_v1_chat_output_proto = out.File
	file_cortex_v1_chat_output_proto_goTypes = nil
	file_cortex_v1_chat_output_proto_depIdxs = nil
}
