// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cortex/v1/chat_input.proto

package cortexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatInferInput is the structured payload a User places inside
// InferRequest.input (the `bytes input` field of model_management.proto). The
// chat capability interprets those bytes as this message instead of as a raw
// completion prompt string.
//
// It mirrors the official OpenAI Chat Completions request body FIELD-FOR-FIELD
// and FLAT (verified against openai-python v1.107.3): field names match OpenAI
// exactly, so an OpenAI-compatible client's request body is a valid
// ChatInferInput as-is (protojson also accepts OpenAI's snake_case keys). No
// vendor-only extension (top_k, min_p, repetition_penalty, min_tokens, ...) is
// accepted.
//
// Fields are grouped by one question: does the field change what gets committed
// and verified?
//
//  1. CONTENT / INTENT  -- messages, tools, tool_choice, response_format,
//     parallel_tool_calls. What the model is asked to do. Free to set.
//
//  2. GENERATION PARAMS -- temperature, top_p, max_completion_tokens, seed,
//     presence_penalty, frequency_penalty, stop. These change WHICH tokens are
//     generated. THIS EXACT SUBSET is what generation_params_digest binds
//     (internal/taskfacts): the order freezes them on-chain, and the Worker
//     applies them from that chain-bound generation context -- NOT from this
//     request. They are therefore REJECTED here (see below): the request carries
//     only content/intent, and the frozen parameters come from the order. (They
//     remain declared so the message still mirrors the OpenAI body field-for-
//     field, and so a reader sees which fields the digest names.)
//
//  3. DELIVERY PREFERENCE -- stream. A transport hint only; streaming
//     reassembles byte-for-byte into the same committed result.
//
// Parser behaviour on the remaining OpenAI fields:
//   - REJECT (fail closed) if present -- they would desynchronise Worker and
//     Verifier, break the single-sample model, or diverge from the frozen
//     parameters, and silently dropping them would answer a different request
//     than the caller sent:
//     temperature, top_p, max_completion_tokens (and the deprecated max_tokens
//     alias), seed, presence_penalty, frequency_penalty,
//     stop -> the generation_params_digest subset, owned
//     by the order's chain-bound generation context and
//     applied from there, not from the request
//     logprobs, top_logprobs  -> the compared logprob COUNT is the profile's
//     required_top_k / compared_top_k
//     logit_bias              -> perturbs the distribution being compared
//     n                       -> must be 1; multi-candidate breaks verification
//   - IGNORE (accept and drop) everything else, so a real OpenAI body still
//     parses: model (resolved from the chain model_id), stream_options, store,
//     metadata, user, service_tier, reasoning_effort, modalities, audio,
//     prediction, web_search_options, prompt_cache_key, safety_identifier, and
//     the deprecated function_call / functions. (Implement as: raw-scan for the
//     rejected keys, then protojson-unmarshal with DiscardUnknown for the rest.)
//
// Free-form JSON sub-structures (tool parameter schemas, tool-call arguments,
// response-format schemas) are carried as JSON strings, matching OpenAI's own
// wire shape (arguments is a stringified JSON) and keeping this schema free of
// a well-known-types dependency; the request builder parses them into objects.
type ChatInferInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// messages is the conversation, oldest first. At least one is required.
	Messages []*ChatMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// tools are the function tools the model may call. Empty disables tool use.
	//
	// Only OpenAI "function" tools are supported; OpenAI's newer "custom" tool
	// type is not modelled. A task that both declares tools AND has the model emit
	// a tool call ends with finish_reason "tool_calls"; the Worker maps that to an
	// in-set FinishReasonV1 (EOS) because the frozen successful-termination enum
	// has no tool_calls member and the Verifier recovers finish_reason by
	// searching that closed set (internal/nodewire, modelservice/finish_reason.go).
	Tools []*ToolDefinition `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	// tool_choice constrains whether/which tool the model calls. Omitted means
	// the server default (auto when tools are present).
	ToolChoice *ToolChoice `protobuf:"bytes,3,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	// parallel_tool_calls allows more than one tool call in a single turn.
	// Absent means the server default.
	ParallelToolCalls *bool `protobuf:"varint,4,opt,name=parallel_tool_calls,json=parallelToolCalls,proto3,oneof" json:"parallel_tool_calls,omitempty"`
	// response_format optionally constrains the output shape (text / json_object
	// / json_schema).
	ResponseFormat *ResponseFormat `protobuf:"bytes,5,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	Temperature    *float64        `protobuf:"fixed64,6,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	TopP           *float64        `protobuf:"fixed64,7,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	// max_completion_tokens is OpenAI's current generation cap. The deprecated
	// OpenAI `max_tokens` alias is rejected too.
	MaxCompletionTokens *int32 `protobuf:"varint,8,opt,name=max_completion_tokens,json=maxCompletionTokens,proto3,oneof" json:"max_completion_tokens,omitempty"`
	// seed is a full signed int64 (OpenAI seed is a signed integer), NOT unsigned.
	Seed             *int64   `protobuf:"varint,9,opt,name=seed,proto3,oneof" json:"seed,omitempty"`
	PresencePenalty  *float64 `protobuf:"fixed64,10,opt,name=presence_penalty,json=presencePenalty,proto3,oneof" json:"presence_penalty,omitempty"`
	FrequencyPenalty *float64 `protobuf:"fixed64,11,opt,name=frequency_penalty,json=frequencyPenalty,proto3,oneof" json:"frequency_penalty,omitempty"`
	// stop are stop sequences (OpenAI allows up to 4). Rejected on input like the
	// other generation params. Beyond that, the chat path does NOT support stop
	// conditions at all: a generation context that carries stop_sequences (or the
	// vLLM-only stop_token_ids) is refused, because a string stop cannot be honoured
	// under the chat path's decode-from-token_ids invariant (the committed output is
	// the concatenated token bytes, which a text-level truncation would desync). Chat
	// generations terminate by natural EOS or max_completion_tokens only. See
	// modelservice/local_chat.go's rejectNonOpenAIChatGenerationParams.
	Stop []string `protobuf:"bytes,12,rep,name=stop,proto3" json:"stop,omitempty"`
	// stream requests incremental delivery of the output to the User. It is a
	// delivery preference only and never alters the committed output, trace,
	// token ids or logprobs.
	Stream        bool `protobuf:"varint,13,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInferInput) Reset() {
	*x = ChatInferInput{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInferInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInferInput) ProtoMessage() {}

func (x *ChatInferInput) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInferInput.ProtoReflect.Descriptor instead.
func (*ChatInferInput) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{0}
}

func (x *ChatInferInput) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatInferInput) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatInferInput) GetToolChoice() *ToolChoice {
	if x != nil {
		return x.ToolChoice
	}
	return nil
}

func (x *ChatInferInput) GetParallelToolCalls() bool {
	if x != nil && x.ParallelToolCalls != nil {
		return *x.ParallelToolCalls
	}
	return false
}

func (x *ChatInferInput) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *ChatInferInput) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ChatInferInput) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *ChatInferInput) GetMaxCompletionTokens() int32 {
	if x != nil && x.MaxCompletionTokens != nil {
		return *x.MaxCompletionTokens
	}
	return 0
}

func (x *ChatInferInput) GetSeed() int64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *ChatInferInput) GetPresencePenalty() float64 {
	if x != nil && x.PresencePenalty != nil {
		return *x.PresencePenalty
	}
	return 0
}

func (x *ChatInferInput) GetFrequencyPenalty() float64 {
	if x != nil && x.FrequencyPenalty != nil {
		return *x.FrequencyPenalty
	}
	return 0
}

func (x *ChatInferInput) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatInferInput) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// ChatMessage is one turn. `role` is "system" | "developer" | "user" |
// "assistant" | "tool".
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// content is the plain-text content of the turn. It may be empty for an
	// assistant turn that only carried tool_calls.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// content_parts is the multimodal form of content (text/image parts). When
	// present it supersedes content. Forward-looking; a text-only first cut may
	// leave it empty.
	ContentParts []*ChatContentPart `protobuf:"bytes,3,rep,name=content_parts,json=contentParts,proto3" json:"content_parts,omitempty"`
	// name optionally distinguishes participants sharing a role.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// tool_calls records, on an assistant turn, the tool calls the model made.
	// Carried in the input only to replay multi-turn history.
	ToolCalls []*ToolCall `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// tool_call_id, on a "tool" turn, names the tool call this message answers.
	ToolCallId    string `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetContentParts() []*ChatContentPart {
	if x != nil {
		return x.ContentParts
	}
	return nil
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

// ChatContentPart is one element of an OpenAI multimodal content array.
type ChatContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is "text" | "image_url" | ... .
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// text is set when type == "text".
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// image_url is set when type == "image_url"; it is the bare URL. OpenAI's wire
	// shape nests it as {"image_url": {"url": ..., "detail": ...}}, so the request
	// builder wraps this value into that object. detail carries the optional
	// OpenAI detail hint ("auto" | "low" | "high"); empty means unset.
	ImageUrl      string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatContentPart) Reset() {
	*x = ChatContentPart{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatContentPart) ProtoMessage() {}

func (x *ChatContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatContentPart.ProtoReflect.Descriptor instead.
func (*ChatContentPart) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{2}
}

func (x *ChatContentPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatContentPart) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ChatContentPart) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ToolDefinition declares one callable tool. type is "function"
// (OpenAI ChatCompletionFunctionToolParam).
type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionDefinition    `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolDefinition) GetFunction() *FunctionDefinition {
	if x != nil {
		return x.Function
	}
	return nil
}

// FunctionDefinition is a callable function's signature
// (OpenAI shared_params.FunctionDefinition).
type FunctionDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// parameters is the argument JSON Schema OBJECT, carried as a JSON string;
	// the builder parses it back into an object for the outgoing request.
	Parameters string `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// strict requests strict schema adherence when the backend supports it.
	Strict        bool `protobuf:"varint,4,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *FunctionDefinition) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// ToolCall is a model-issued call, replayed from assistant history
// (OpenAI ChatCompletionMessageFunctionToolCallParam).
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is "function".
	Type          string        `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionCall `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *FunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

// FunctionCall names the function and its arguments. arguments is a
// JSON-encoded string, matching OpenAI's wire shape.
type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// ToolChoice selects the tool-calling policy
// (OpenAI ChatCompletionToolChoiceOptionParam).
type ToolChoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mode is "none" | "auto" | "required". Empty means the server default.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// function_name pins a specific function (OpenAI's named form
	// {type:"function", function:{name}}). When set, mode is ignored.
	FunctionName  string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolChoice) Reset() {
	*x = ToolChoice{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChoice) ProtoMessage() {}

func (x *ToolChoice) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChoice.ProtoReflect.Descriptor instead.
func (*ToolChoice) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{7}
}

func (x *ToolChoice) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ToolChoice) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

// ResponseFormat constrains the output shape (OpenAI response_format union).
type ResponseFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is "text" | "json_object" | "json_schema".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// json_schema, when type == "json_schema", is a JSON string carrying OpenAI's
	// ResponseFormatJSONSchema.json_schema OBJECT -- {"name","description",
	// "schema","strict"} -- not the bare JSON Schema. The builder passes it
	// through as response_format.json_schema.
	JsonSchema    string `protobuf:"bytes,2,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormat) Reset() {
	*x = ResponseFormat{}
	mi := &file_cortex_v1_chat_input_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormat) ProtoMessage() {}

func (x *ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_v1_chat_input_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormat.ProtoReflect.Descriptor instead.
func (*ResponseFormat) Descriptor() ([]byte, []int) {
	return file_cortex_v1_chat_input_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseFormat) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

var File_cortex_v1_chat_input_proto protoreflect.FileDescriptor

const file_cortex_v1_chat_input_proto_rawDesc = "" +
	"\n" +
	"\x1acortex/v1/chat_input.proto\x12\tcortex.v1\"\xc7\x05\n" +
	"\x0eChatInferInput\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.cortex.v1.ChatMessageR\bmessages\x12/\n" +
	"\x05tools\x18\x02 \x03(\v2\x19.cortex.v1.ToolDefinitionR\x05tools\x126\n" +
	"\vtool_choice\x18\x03 \x01(\v2\x15.cortex.v1.ToolChoiceR\n" +
	"toolChoice\x123\n" +
	"\x13parallel_tool_calls\x18\x04 \x01(\bH\x00R\x11parallelToolCalls\x88\x01\x01\x12B\n" +
	"\x0fresponse_format\x18\x05 \x01(\v2\x19.cortex.v1.ResponseFormatR\x0eresponseFormat\x12%\n" +
	"\vtemperature\x18\x06 \x01(\x01H\x01R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\a \x01(\x01H\x02R\x04topP\x88\x01\x01\x127\n" +
	"\x15max_completion_tokens\x18\b \x01(\x05H\x03R\x13maxCompletionTokens\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\t \x01(\x03H\x04R\x04seed\x88\x01\x01\x12.\n" +
	"\x10presence_penalty\x18\n" +
	" \x01(\x01H\x05R\x0fpresencePenalty\x88\x01\x01\x120\n" +
	"\x11frequency_penalty\x18\v \x01(\x01H\x06R\x10frequencyPenalty\x88\x01\x01\x12\x12\n" +
	"\x04stop\x18\f \x03(\tR\x04stop\x12\x16\n" +
	"\x06stream\x18\r \x01(\bR\x06streamB\x16\n" +
	"\x14_parallel_tool_callsB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\x18\n" +
	"\x16_max_completion_tokensB\a\n" +
	"\x05_seedB\x13\n" +
	"\x11_presence_penaltyB\x14\n" +
	"\x12_frequency_penalty\"\xe6\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12?\n" +
	"\rcontent_parts\x18\x03 \x03(\v2\x1a.cortex.v1.ChatContentPartR\fcontentParts\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x13.cortex.v1.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallId\"n\n" +
	"\x0fChatContentPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"_\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\bfunction\x18\x02 \x01(\v2\x1d.cortex.v1.FunctionDefinitionR\bfunction\"\x82\x01\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12\x16\n" +
	"\x06strict\x18\x04 \x01(\bR\x06strict\"c\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x123\n" +
	"\bfunction\x18\x03 \x01(\v2\x17.cortex.v1.FunctionCallR\bfunction\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"E\n" +
	"\n" +
	"ToolChoice\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\"E\n" +
	"\x0eResponseFormat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vjson_schema\x18\x02 \x01(\tR\n" +
	"jsonSchemaB1Z/github.com/TrueOpen/wire/gen/cortex/v1;cortexv1b\x06proto3"

var (
	file_cortex_v1_chat_input_proto_rawDescOnce sync.Once
	file_cortex_v1_chat_input_proto_rawDescData []byte
)

func file_cortex_v1_chat_input_proto_rawDescGZIP() []byte {
	file_cortex_v1_chat_input_proto_rawDescOnce.Do(func() {
		file_cortex_v1_chat_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_v1_chat_input_proto_rawDesc), len(file_cortex_v1_chat_input_proto_rawDesc)))
	})
	return file_cortex_v1_chat_input_proto_rawDescData
}

var file_cortex_v1_chat_input_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cortex_v1_chat_input_proto_goTypes = []any{
	(*ChatInferInput)(nil),     // 0: cortex.v1.ChatInferInput
	(*ChatMessage)(nil),        // 1: cortex.v1.ChatMessage
	(*ChatContentPart)(nil),    // 2: cortex.v1.ChatContentPart
	(*ToolDefinition)(nil),     // 3: cortex.v1.ToolDefinition
	(*FunctionDefinition)(nil), // 4: cortex.v1.FunctionDefinition
	(*ToolCall)(nil),           // 5: cortex.v1.ToolCall
	(*FunctionCall)(nil),       // 6: cortex.v1.FunctionCall
	(*ToolChoice)(nil),         // 7: cortex.v1.ToolChoice
	(*ResponseFormat)(nil),     // 8: cortex.v1.ResponseFormat
}
var file_cortex_v1_chat_input_proto_depIdxs = []int32{
	1, // 0: cortex.v1.ChatInferInput.messages:type_name -> cortex.v1.ChatMessage
	3, // 1: cortex.v1.ChatInferInput.tools:type_name -> cortex.v1.ToolDefinition
	7, // 2: cortex.v1.ChatInferInput.tool_choice:type_name -> cortex.v1.ToolChoice
	8, // 3: cortex.v1.ChatInferInput.response_format:type_name -> cortex.v1.ResponseFormat
	2, // 4: cortex.v1.ChatMessage.content_parts:type_name -> cortex.v1.ChatContentPart
	5, // 5: cortex.v1.ChatMessage.tool_calls:type_name -> cortex.v1.ToolCall
	4, // 6: cortex.v1.ToolDefinition.function:type_name -> cortex.v1.FunctionDefinition
	6, // 7: cortex.v1.ToolCall.function:type_name -> cortex.v1.FunctionCall
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cortex_v1_chat_input_proto_init() }
func file_cortex_v1_chat_input_proto_init() {
	if File_cortex_v1_chat_input_proto != nil {
		return
	}
	file_cortex_v1_chat_input_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_v1_chat_input_proto_rawDesc), len(file_cortex_v1_chat_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cortex_v1_chat_input_proto_goTypes,
		DependencyIndexes: file_cortex_v1_chat_input_proto_depIdxs,
		MessageInfos:      file_cortex_v1_chat_input_proto_msgTypes,
	}.Build()
	File_cortex_v1_chat_input_proto = out.File
	file_cortex_v1_chat_input_proto_goTypes = nil
	file_cortex_v1_chat_input_proto_depIdxs = nil
}
