// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: cortex/v1/model_management.proto

package cortexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelManagementService_Health_FullMethodName           = "/cortex.v1.ModelManagementService/Health"
	ModelManagementService_ListCapabilities_FullMethodName = "/cortex.v1.ModelManagementService/ListCapabilities"
	ModelManagementService_GetModelDetails_FullMethodName  = "/cortex.v1.ModelManagementService/GetModelDetails"
	ModelManagementService_LoadModel_FullMethodName        = "/cortex.v1.ModelManagementService/LoadModel"
	ModelManagementService_Estimate_FullMethodName         = "/cortex.v1.ModelManagementService/Estimate"
	ModelManagementService_Infer_FullMethodName            = "/cortex.v1.ModelManagementService/Infer"
	ModelManagementService_Verify_FullMethodName           = "/cortex.v1.ModelManagementService/Verify"
	ModelManagementService_FetchArtifact_FullMethodName    = "/cortex.v1.ModelManagementService/FetchArtifact"
)

// ModelManagementServiceClient is the client API for ModelManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelManagementService is the Cortex/model-service boundary: the RPCs a Cortex
// node uses to discover what a model service can run, to run one inference or
// one verification, and to stream the resulting artifacts back.
//
// It is NOT a chain-facing contract. Nothing here is signed or hashed into a
// protocol commitment; the committed material is derived by Cortex from what
// these calls return. Its stability requirement is therefore an operational one
// (a Cortex and a model service deployed together must agree), not a consensus
// one.
type ModelManagementServiceClient interface {
	// Health reports whether the service can accept work at all. It is the
	// cheapest call and the one a readiness probe uses.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ListCapabilities reports which (model, capability) pairs the service can
	// serve and how much concurrency is left, so a node can decide whether to
	// raise its hand for a task.
	ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error)
	// GetModelDetails returns the installed model's artifact digests and config
	// summary. Cortex derives the registration manifest from this, so the values
	// must describe the files actually on disk.
	GetModelDetails(ctx context.Context, in *GetModelDetailsRequest, opts ...grpc.CallOption) (*GetModelDetailsResponse, error)
	// LoadModel asks the service to make one model resident. It is idempotent: a
	// model already loaded is a success, not a conflict.
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	// Estimate predicts cost and duration for a prospective job without running
	// it, so a node can refuse work it cannot finish before the deadline.
	Estimate(ctx context.Context, in *EstimateRequest, opts ...grpc.CallOption) (*EstimateResponse, error)
	// Infer runs one generation. The response carries artifact references rather
	// than bytes; the caller streams the bytes back with FetchArtifact.
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
	// Verify re-derives a Worker's evidence by teacher-forcing over the token
	// sequence that Worker already produced, and returns the per-position
	// comparison the verifier turns into a result credential.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// FetchArtifact streams one artifact named by a reference from an earlier
	// Infer or Verify response.
	FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error)
}

type modelManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelManagementServiceClient(cc grpc.ClientConnInterface) ModelManagementServiceClient {
	return &modelManagementServiceClient{cc}
}

func (c *modelManagementServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_ListCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) GetModelDetails(ctx context.Context, in *GetModelDetailsRequest, opts ...grpc.CallOption) (*GetModelDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelDetailsResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_GetModelDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Estimate(ctx context.Context, in *EstimateRequest, opts ...grpc.CallOption) (*EstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_Estimate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, ModelManagementService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelManagementService_ServiceDesc.Streams[0], ModelManagementService_FetchArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchArtifactRequest, ArtifactChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelManagementService_FetchArtifactClient = grpc.ServerStreamingClient[ArtifactChunk]

// ModelManagementServiceServer is the server API for ModelManagementService service.
// All implementations must embed UnimplementedModelManagementServiceServer
// for forward compatibility.
//
// ModelManagementService is the Cortex/model-service boundary: the RPCs a Cortex
// node uses to discover what a model service can run, to run one inference or
// one verification, and to stream the resulting artifacts back.
//
// It is NOT a chain-facing contract. Nothing here is signed or hashed into a
// protocol commitment; the committed material is derived by Cortex from what
// these calls return. Its stability requirement is therefore an operational one
// (a Cortex and a model service deployed together must agree), not a consensus
// one.
type ModelManagementServiceServer interface {
	// Health reports whether the service can accept work at all. It is the
	// cheapest call and the one a readiness probe uses.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ListCapabilities reports which (model, capability) pairs the service can
	// serve and how much concurrency is left, so a node can decide whether to
	// raise its hand for a task.
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error)
	// GetModelDetails returns the installed model's artifact digests and config
	// summary. Cortex derives the registration manifest from this, so the values
	// must describe the files actually on disk.
	GetModelDetails(context.Context, *GetModelDetailsRequest) (*GetModelDetailsResponse, error)
	// LoadModel asks the service to make one model resident. It is idempotent: a
	// model already loaded is a success, not a conflict.
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	// Estimate predicts cost and duration for a prospective job without running
	// it, so a node can refuse work it cannot finish before the deadline.
	Estimate(context.Context, *EstimateRequest) (*EstimateResponse, error)
	// Infer runs one generation. The response carries artifact references rather
	// than bytes; the caller streams the bytes back with FetchArtifact.
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	// Verify re-derives a Worker's evidence by teacher-forcing over the token
	// sequence that Worker already produced, and returns the per-position
	// comparison the verifier turns into a result credential.
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// FetchArtifact streams one artifact named by a reference from an earlier
	// Infer or Verify response.
	FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error
	mustEmbedUnimplementedModelManagementServiceServer()
}

// UnimplementedModelManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelManagementServiceServer struct{}

func (UnimplementedModelManagementServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedModelManagementServiceServer) ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCapabilities not implemented")
}
func (UnimplementedModelManagementServiceServer) GetModelDetails(context.Context, *GetModelDetailsRequest) (*GetModelDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelDetails not implemented")
}
func (UnimplementedModelManagementServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedModelManagementServiceServer) Estimate(context.Context, *EstimateRequest) (*EstimateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Estimate not implemented")
}
func (UnimplementedModelManagementServiceServer) Infer(context.Context, *InferRequest) (*InferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedModelManagementServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedModelManagementServiceServer) FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchArtifact not implemented")
}
func (UnimplementedModelManagementServiceServer) mustEmbedUnimplementedModelManagementServiceServer() {
}
func (UnimplementedModelManagementServiceServer) testEmbeddedByValue() {}

// UnsafeModelManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelManagementServiceServer will
// result in compilation errors.
type UnsafeModelManagementServiceServer interface {
	mustEmbedUnimplementedModelManagementServiceServer()
}

func RegisterModelManagementServiceServer(s grpc.ServiceRegistrar, srv ModelManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedModelManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelManagementService_ServiceDesc, srv)
}

func _ModelManagementService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_ListCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).ListCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_ListCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_GetModelDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).GetModelDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_GetModelDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).GetModelDetails(ctx, req.(*GetModelDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Estimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Estimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_Estimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Estimate(ctx, req.(*EstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelManagementService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_FetchArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelManagementServiceServer).FetchArtifact(m, &grpc.GenericServerStream[FetchArtifactRequest, ArtifactChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelManagementService_FetchArtifactServer = grpc.ServerStreamingServer[ArtifactChunk]

// ModelManagementService_ServiceDesc is the grpc.ServiceDesc for ModelManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.v1.ModelManagementService",
	HandlerType: (*ModelManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ModelManagementService_Health_Handler,
		},
		{
			MethodName: "ListCapabilities",
			Handler:    _ModelManagementService_ListCapabilities_Handler,
		},
		{
			MethodName: "GetModelDetails",
			Handler:    _ModelManagementService_GetModelDetails_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _ModelManagementService_LoadModel_Handler,
		},
		{
			MethodName: "Estimate",
			Handler:    _ModelManagementService_Estimate_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _ModelManagementService_Infer_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _ModelManagementService_Verify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchArtifact",
			Handler:       _ModelManagementService_FetchArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cortex/v1/model_management.proto",
}
