// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.36.0
// source: cortex/v1/model_management.proto

package cortexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ModelManagementServiceClient is the client API for ModelManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelManagementServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error)
	GetModelDetails(ctx context.Context, in *GetModelDetailsRequest, opts ...grpc.CallOption) (*GetModelDetailsResponse, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	Estimate(ctx context.Context, in *EstimateRequest, opts ...grpc.CallOption) (*EstimateResponse, error)
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (ModelManagementService_FetchArtifactClient, error)
}

type modelManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelManagementServiceClient(cc grpc.ClientConnInterface) ModelManagementServiceClient {
	return &modelManagementServiceClient{cc}
}

func (c *modelManagementServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error) {
	out := new(ListCapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/ListCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) GetModelDetails(ctx context.Context, in *GetModelDetailsRequest, opts ...grpc.CallOption) (*GetModelDetailsResponse, error) {
	out := new(GetModelDetailsResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/GetModelDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/LoadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Estimate(ctx context.Context, in *EstimateRequest, opts ...grpc.CallOption) (*EstimateResponse, error) {
	out := new(EstimateResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/Estimate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/Infer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/cortex.v1.ModelManagementService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelManagementServiceClient) FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (ModelManagementService_FetchArtifactClient, error) {
	stream, err := c.cc.NewStream(ctx, &ModelManagementService_ServiceDesc.Streams[0], "/cortex.v1.ModelManagementService/FetchArtifact", opts...)
	if err != nil {
		return nil, err
	}
	x := &modelManagementServiceFetchArtifactClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModelManagementService_FetchArtifactClient interface {
	Recv() (*ArtifactChunk, error)
	grpc.ClientStream
}

type modelManagementServiceFetchArtifactClient struct {
	grpc.ClientStream
}

func (x *modelManagementServiceFetchArtifactClient) Recv() (*ArtifactChunk, error) {
	m := new(ArtifactChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ModelManagementServiceServer is the server API for ModelManagementService service.
// All implementations must embed UnimplementedModelManagementServiceServer
// for forward compatibility
type ModelManagementServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error)
	GetModelDetails(context.Context, *GetModelDetailsRequest) (*GetModelDetailsResponse, error)
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	Estimate(context.Context, *EstimateRequest) (*EstimateResponse, error)
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	FetchArtifact(*FetchArtifactRequest, ModelManagementService_FetchArtifactServer) error
	mustEmbedUnimplementedModelManagementServiceServer()
}

// UnimplementedModelManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModelManagementServiceServer struct {
}

func (UnimplementedModelManagementServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedModelManagementServiceServer) ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCapabilities not implemented")
}
func (UnimplementedModelManagementServiceServer) GetModelDetails(context.Context, *GetModelDetailsRequest) (*GetModelDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelDetails not implemented")
}
func (UnimplementedModelManagementServiceServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedModelManagementServiceServer) Estimate(context.Context, *EstimateRequest) (*EstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Estimate not implemented")
}
func (UnimplementedModelManagementServiceServer) Infer(context.Context, *InferRequest) (*InferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedModelManagementServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedModelManagementServiceServer) FetchArtifact(*FetchArtifactRequest, ModelManagementService_FetchArtifactServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchArtifact not implemented")
}
func (UnimplementedModelManagementServiceServer) mustEmbedUnimplementedModelManagementServiceServer() {
}

// UnsafeModelManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelManagementServiceServer will
// result in compilation errors.
type UnsafeModelManagementServiceServer interface {
	mustEmbedUnimplementedModelManagementServiceServer()
}

func RegisterModelManagementServiceServer(s grpc.ServiceRegistrar, srv ModelManagementServiceServer) {
	s.RegisterService(&ModelManagementService_ServiceDesc, srv)
}

func _ModelManagementService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_ListCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).ListCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/ListCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_GetModelDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).GetModelDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/GetModelDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).GetModelDetails(ctx, req.(*GetModelDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/LoadModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Estimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Estimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/Estimate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Estimate(ctx, req.(*EstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/Infer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelManagementServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cortex.v1.ModelManagementService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelManagementServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelManagementService_FetchArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelManagementServiceServer).FetchArtifact(m, &modelManagementServiceFetchArtifactServer{stream})
}

type ModelManagementService_FetchArtifactServer interface {
	Send(*ArtifactChunk) error
	grpc.ServerStream
}

type modelManagementServiceFetchArtifactServer struct {
	grpc.ServerStream
}

func (x *modelManagementServiceFetchArtifactServer) Send(m *ArtifactChunk) error {
	return x.ServerStream.SendMsg(m)
}

// ModelManagementService_ServiceDesc is the grpc.ServiceDesc for ModelManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.v1.ModelManagementService",
	HandlerType: (*ModelManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _ModelManagementService_Health_Handler,
		},
		{
			MethodName: "ListCapabilities",
			Handler:    _ModelManagementService_ListCapabilities_Handler,
		},
		{
			MethodName: "GetModelDetails",
			Handler:    _ModelManagementService_GetModelDetails_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _ModelManagementService_LoadModel_Handler,
		},
		{
			MethodName: "Estimate",
			Handler:    _ModelManagementService_Estimate_Handler,
		},
		{
			MethodName: "Infer",
			Handler:    _ModelManagementService_Infer_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _ModelManagementService_Verify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchArtifact",
			Handler:       _ModelManagementService_FetchArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cortex/v1/model_management.proto",
}
